### ISSUE TITLE
[Feature request] mpv-stats integration

### ISSUE THREAD

**Issue by adamkex** [cmdrkotori/mpc-qt#104]
Is it possible to integrate mpv-stats (or similar functionality) into the media player?

https://github.com/Argon-/mpv-stats (GPL 2.0 Licence)

**Comment by cmdrkotori** [comment]
Anything is possible when you have the source code.

**Comment by ehea617** [comment]
CTRL+J was the keyboard shortcut for the equivalent feature in MPC-HC.

**Comment by cmdrkotori** [comment]
Okay thanks I'll have a look at it.

**Comment by ahjolinna** [comment]
bomi-player had something like this: 
![image](https://user-images.githubusercontent.com/6993072/28751709-85508246-7517-11e7-86f0-6ca9cf93e0ef.png)
[source/commit ](https://github.com/xylosper/bomi/commit/d975971e5e9fcb4321400dc1cdc32bfbb409192d)

....yes with a horrible yellow font...for some reason

**Comment by cmdrkotori** [comment]
Fixed, with a small mystery bug that needs more investigation as mentioned in the commit message.
