### ISSUE TITLE
VapourSynth

### ISSUE THREAD

**Issue by brucethemoose** [cmdrkotori/mpc-qt#105]
Could you compile future Windows releases with the "--enable-vapoursynth" MPV flag? Among other things, this would let it work with SVP out of the box. 

_______________________________________________________

On a related note, could we get a VapourSynth GUI in the future? I was specifically thinking of PotPlayer's:

http://i.cubeupload.com/Mnt7iv.png

That script, as an example, would deinterlance a DVD with better IQ than MPV (or pretty much any video player) would, assuming you have an OK CPU. And that's just the tip of the iceberg. Basically, if you need something specific that MPV or a shader doesn't do by default, you could probably implement it as a VS script. 

Even then, I know that's a pretty small niche involving a lot of work, and it would increase the size of the release a bit with the VS/python binaries you'd need to include... So maybe make it a low-priority feature? I'd be happy to make some script presets, if needed.

**Comment by brucethemoose** [comment]
And to be clear, this is already a MPV feature:

https://mpv.io/manual/master/#video-filters-vapoursynth

Basically QT would just generate the text file.

**Comment by ahjolinna** [comment]
if I remember correctly mpc-qt uses some [prebuild MPV](https://mpv.srsfckn.biz/), that would mean you would need to ask the maintainer who provides that build to make that change or @cmdrkotori needs to make his own build...this oc mean including the vapoursynth binary also.

anyway, about the GUI thing, there is [editor made in qt5](https://bitbucket.org/mystery_keeper/vapoursynth-editor) (under MIT license) that @cmdrkotori  could "fork" to mpc-qt..found about it here: http://forum.doom9.org/showthread.php?p=1688477

**Comment by cmdrkotori** [comment]
@lachs0r is the dude who compiles libmpv, ask him. The right place for this is probably [over here](https://github.com/lachs0r/mingw-w64-cmake/). If i recally correctly, the reason why they don't come with vapoursynth is because it's a real pain to get python working on Windows.
