### ISSUE TITLE
"Disable screensaver while playing" option does not function in Windows 10

### ISSUE THREAD

**Issue by adamkex** [cmdrkotori/mpc-qt#107]
I have the option ticked and the screensaver still shows up for me. I use Windows 10 and an integrated Intel GPU.

**Comment by cmdrkotori** [comment]
Let me know if it doesn't work. I couldn't test this because my Windows 10 vm did not activate the selected Pipes screensaver despite it being idle for some time.

**Comment by adamkex** [comment]
I tested in on my main PC and it still doesn't work. It also runs Windows 10 but uses an Nvidia GTX 970.

**Comment by adamkex** [comment]
Actually scratch that. I've not compiled the latest mpc-qt (I have no compiler) so I can test this feature in your next Windows release.

**Comment by cmdrkotori** [comment]
I just tested and can confirm that it works now.

Yes, this will be in the next release.
