### ISSUE TITLE
disable subs?

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#110]
I just notice that if you select some subtitle and then want to unselect/disable subtitles completely...you can't...there is "none/disable" option (in "Play->Subtitles->")

**Comment by cmdrkotori** [comment]
Yeah this has been bothering me for a bit.

**Comment by ahjolinna** [comment]
I know you are maybe getting tired of me saying this, but bomi has done it like this:

![image](https://user-images.githubusercontent.com/6993072/29201412-a9abf532-7e66-11e7-97b4-fce20949c12a.png)

-------------------------

I don't know what you think about the "context menu" thing in general, I find that at least basic things could be moved to it ....like at least audio/sub settings

**Comment by cmdrkotori** [comment]
Fixed. However, the right click menu remains unimplementented.
