### ISSUE TITLE
"context menu" / "right click menu"

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#113]
I don't know how you feel about this, but I think a "context menu" would be nice to have to make some stuff simple/faster to access, as currently all the options at the menu bar is little bit cluttered and this would remove most/some of it :

again, as an example what option the bomi player had  :
![image](https://user-images.githubusercontent.com/6993072/29249174-7f6d6b2e-8033-11e7-8c00-3dd3c6ee9443.png) ![image](https://user-images.githubusercontent.com/6993072/29249182-8cd97226-8033-11e7-888f-196badd2a994.png)
![image](https://user-images.githubusercontent.com/6993072/29249195-ae276492-8033-11e7-84c1-6809c35d8ef8.png)
![image](https://user-images.githubusercontent.com/6993072/29249204-c0d19248-8033-11e7-8822-061afdc0515b.png)
![image](https://user-images.githubusercontent.com/6993072/29249205-cc6cd4e6-8033-11e7-8eec-2fe0d41fa967.png)
![image](https://user-images.githubusercontent.com/6993072/29249210-dac4adfc-8033-11e7-8e20-1f388474c4bb.png)
![image](https://user-images.githubusercontent.com/6993072/29249217-ed9330a2-8033-11e7-8bb3-df88eb6f07c3.png)

if this would be added I don't think every option needs to be added (like bomi has done), the core features should do fine.

**Comment by ahjolinna** [comment]
also if you are open to this, it would be nice to have conversation of what will and wont be added to the "context menu"

**Comment by cmdrkotori** [comment]
I'll probably be copying most of mpc-hc that makes sense, followed by ideas from mpc-be, bomi and vlc.

**Comment by ahjolinna** [comment]
I love that the core "look & fee" is like MPC-HC _('requiesce in pace')_  but that doesn't mean it's perfect. 

Also this wouldn't replace the original menu bar solution, just enhance the experience. Not every functionality needs to be "seek and find"... As unfortunately humans memory in general is really bad (I think it's only 60% accurate) 

_Sent from my Sony F5121 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ahjolinna** [comment]
thank you...anyway, I'm not entirely sure if every option is needed as it feels little bit ...redundant ...?...(I think that is word I'm looking for)...when they already exist in the menu bar.

I would trim down some the options in "File" and maybe remove "After playback", "View" & "Properties" completely ...and then "Options" I have mixed feelings about

------

also why is exit/quit shortcut "alt+x" ? ...it's usually "Ctrl+q"
--------

if you want to talk more in some "chat", I can be found at Discord and IRC/freenode....with the same nick.
