### ISSUE TITLE
mpc-qt sometimes opens in a maximized window using a fraction of the window on Linux.

### ISSUE THREAD

**Issue by kah0922** [cmdrkotori/mpc-qt#114]
Sorry for the vague title, it's kind of hard to explain this.
Sometimes (regardless of video resolution, I've tested it with various resolutions) mpc-qt will open in a window like [this](https://i.imgur.com/vzu3toy.png).
![Screenshot](https://i.imgur.com/vzu3toyl.png)

I am using the latest openSUSE Tumbleweed KDE on the lastest git snapshot of mpc-qt.

**Comment by ahjolinna** [comment]
I haven't notice this on Arch (+KDE), have you tired any debugging? (gdb) _...also remember to enable it in the "Miscellaneous" settings options._

--------------

my system:
```
inxi -b
System:    Host: arch-anywhere Kernel: 4.11.12-1-ck-skylake x86_64 (64 bit) Desktop: KDE Plasma 5.10.4
           Distro: Arch Linux
Machine:   Device: desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x UEFI: American Megatrends v: 2003 date: 09/19/2016
CPU:       Quad core Intel Core i5-6600K (-MCP-) speed/max: 4399/4400 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 version: 4.5.0 NVIDIA 384.59
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e
Drives:    HDD Total Size: 12114.3GB (95.2% used)
Info:      Processes: 308 Uptime: 21:17 Memory: 8899.9/15966.9MB Client: Shell (bash) inxi: 2.3.27
```

**Comment by kah0922** [comment]
I honestly don't have any clue how to use gdb.

I can, however reproduce this regularly now.

> 1. Open a file with mpc-qt using a file manager (Dolphin in my case)
> 2. Maximize mpc-qt and then close.
> 3. Reopen the same video file and the above bug happens.

And my system:
```
System:    Host: localhost.localdomain Kernel: 4.11.8-2-default x86_64 (64 bit) Desktop: KDE Plasma 5.10.4
           Distro: openSUSE Tumbleweed 20170810
Machine:   Device: desktop Mobo: MSI model: B250M PRO-VD(MS-7A74) v: 1.0 UEFI: American Megatrends v: 1.40 date: 04/06/2017
CPU:       Dual core Intel Pentium G4560 (-HT-MCP-) speed/max: 799/3500 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Baffin [Radeon RX 460]
           Display Server: x11 (X.org 1.19.3) drivers: amdgpu (unloaded: modesetting) tty size: 212x28
Network:   Card-1: Intel Wireless 8260 driver: iwlwifi
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller driver: r8169
Drives:    HDD Total Size: 1000.2GB (70.7% used)
Info:      Processes: 228 Uptime: 2:53 Memory: 3193.7/7951.4MB Init: systemd runlevel: 5
           Client: Shell (bash) inxi: 2.3.25 
```

**Comment by ahjolinna** [comment]
I still can't reproduce that on Arch (desktop) nor ChakraOS (ultrabook)

about [GDB, check arch wiki](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Gdb) (the best linux guide)

-----
my chakraOS/ultrabook:

```
inxi -b
System:    Host: acer-aspire Kernel: 4.12.4-1-CHAKRA x86_64 (64 bit) Desktop: KDE Plasma 5.10.4 Distro: Chakra
Machine:   Device: laptop System: Acer product: Aspire S7-191 v: V2.18
           Mobo: Acer model: Helium v: V2.18 UEFI: Insyde v: V2.18 date: 12/09/2013
Battery    BAT0: charge: 33.5 Wh 100.0% condition: 33.5/39.1 Wh (86%)
CPU:       Dual core Intel Core i3-3217U (-HT-MCP-) speed/max: 799/1800 MHz
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           Display Server: x11 (X.Org 1.19.3) driver: intel Resolution: 1920x1080@60.00hz
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile version: 4.2 Mesa 17.1.5
Network:   Card: Qualcomm Atheros AR9462 Wireless Network Adapter driver: ath9k
Drives:    HDD Total Size: 128.0GB (10.9% used)
Info:      Processes: 263 Uptime: 10:16 Memory: 695.6/3845.9MB Client: Shell (bash) inxi: 2.3.23
```


_(I just hope this isn't another AMD/radeon driver problem...I'm getting tired with amd/radeon because of its endless problems...yes its getting better but too slow and late, at least for me)_

**Comment by ahjolinna** [comment]
oh and remember to enable debugging in mpc-qt/mpv also:
![image](https://user-images.githubusercontent.com/6993072/29253505-8944983a-8087-11e7-9aff-88cac0c811b7.png)

**Comment by kah0922** [comment]
Here it is. I reproduced the same scenario as before, so this has the file opened twice. 
https://gist.github.com/kah0922/994b2d4f787c32aa3bc2672a0b6193a2

**Comment by ahjolinna** [comment]
I hope @cmdrkotori finds the logs useful...

@kah0922 : I was wondering as you are using openSUSE (tumbleweed) and theirs ffmpeg doesn't provide any proprietary codecs or even x264 or hevc for that matter (even when fedora and other distros do) I assume you have the [packman](https://en.opensuse.org/Additional_package_repositories#Packman) repos in use to get those codecs...right?

**Comment by cmdrkotori** [comment]
From my testing, the windowing code falls apart when the playlist window isn't docked. (I always have it docked.) Don't feel too bad about it, it's the asynchronous nature of X that I thought I had coded around, but apparently not always.

**Comment by kah0922** [comment]
I have the playlist window disabled so that's probably why I encountered that.

**Comment by ahjolinna** [comment]
on arch I have the playlist disabled also, and on chakraOS it was undocked

**Comment by kah0922** [comment]
Just updated my package to the latest git and everything works now.
