### ISSUE TITLE
[question] Qbs?

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#115]
what is Qbs?
_Qbs (pronounced “Cubes”) is The Qt Company’s latest build tool, which is planned to be the replacement for qmake in the Qt 6 build system_

[Qbs v1.8](http://blog.qt.io/blog/2017/05/29/qbs-1-8-released/) was released few months ago, yes it will become more relevant when Qt6 arrives end of next year (?), but as Qbs can already be used with Qt5 maybe try to make a preliminary support? also have you ever checked Qbs out, and what is required for mpc-qt become compatible with it?

I have been reading that some features are still missing from Qbs v1.8 (stability release), but the next v1.9 release should be more feature rich, which should arrive soon™ (month or so)

------------

PS. this also reminded me, the [clazy](https://github.com/KDE/clazy) project has improved a lot since last time (+ better documentation) I told you about this (#80)

-----

and here is [MakeGirls.moe](http://make.girls.moe/) project ([github](https://github.com/makegirlsmoe)) to make your every day better

**Comment by cmdrkotori** [comment]
I'll take a look at it. However I might have to wait until ubuntu 18.04 for actual use so that most people will have access to it. Also, thank you for the reminders about clazy.

**Comment by ahjolinna** [comment]
well I think this can be closed then...

-----------
side note: [btw. (PlatinumGames Co-Founder) Hideki Kamiya Thanked Yoko Taro for "Saving" PlatinumGames with NieR: Automata]( http://www.dualshockers.com/hideki-kamiya-thanks-yoko-taro-saving-platinumgames-nier-automata/)  ...it's a jrpg  you really need to checkout if you have a PS4(pro) (there is a demo) or good PC (no Linux version yet)

**Comment by ahjolinna** [comment]
@cmdrkotori : not really reopening this but have you checked Qbs at least now with latest [v1.12 release](https://blog.qt.io/blog/2018/07/19/qbs-1-12-released/) (included in Qt Creator 4.7.0, which was released this week as well)

here is a list what version of Qbs distros have: https://repology.org/metapackage/qbs/versions
