### ISSUE TITLE
File->Save Image (Alt-I) Doesn't Work on Windows

### ISSUE THREAD

**Issue by ehea617** [cmdrkotori/mpc-qt#120]
File->Save Image (Alt-I) doesn't work on Windows, however Save Image (Auto) does. The file is never created using File->Save Image (Alt-I). My current settings for screenshot encoding are:
![image](https://user-images.githubusercontent.com/12926544/29793425-beeb0f7e-8c11-11e7-9cad-b28fb34113b5.png)
It is also worth noting that this issue also occurs with encoding set to jpg, Save Plain Image, and Save Window Image.

**Comment by ahjolinna** [comment]
it's same on linux, the "Alt-I" does create a screenshot...it just saves it to the /tmp/* folder

```
"[cplayer] v: Run command: screenshot-to-file, flags=0, args=[/tmp/mpc-qt_{71b7df1d-3b29-4ddb-b830-96223e7e131d}, video]\n"
"[cplayer] info: Screenshot: '/tmp/mpc-qt_{71b7df1d-3b29-4ddb-b830-96223e7e131d}'\n"

```

auto option does work just fine:
```
"[cplayer] v: Run command: screenshot-to-file, flags=0, args=[/home/ahjolinna/Pictures/mpc_shots/House MD Season 3 Episode 05 - Fools for Love_snapshot_00:00:06.631_[2017.08.29_06.38.53].png, video]\n"
"[cplayer] info: Screenshot: '/home/ahjolinna/Pictures/mpc_shots/House MD Season 3 Episode 05 - Fools for Love_snapshot_00:00:06.631_[2017.08.29_06.38.53].png'\n"
```
