### ISSUE TITLE
many settings options are "disabled" (linux)

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#121]
when I check the settings option there are many things that I can't "touch" at all because they are "disabled" (check added pics), are there some dependencies missing (on AUR?) or is this because it's incompatible with latest mpv changes.
(this has been "broken" for a while, I just haven't reported this)

![image](https://user-images.githubusercontent.com/6993072/29821114-76638dc6-8ccf-11e7-8185-1a8bb0739c7f.png)
![image](https://user-images.githubusercontent.com/6993072/29820689-fdd91912-8ccd-11e7-934e-ef221e21755c.png)
![image](https://user-images.githubusercontent.com/6993072/29820600-b7e92c12-8ccd-11e7-871a-e5ad8f7b8cdb.png)
![image](https://user-images.githubusercontent.com/6993072/29820626-cdb0e684-8ccd-11e7-89a7-0515d8a996cb.png)
![image](https://user-images.githubusercontent.com/6993072/29820634-d71733c2-8ccd-11e7-8cba-19006800307f.png)
![image](https://user-images.githubusercontent.com/6993072/29820571-9c8975d0-8ccd-11e7-913d-9f94f99495d4.png)
![image](https://user-images.githubusercontent.com/6993072/29820588-a75a46a6-8ccd-11e7-90be-19b356557d26.png)
![image](https://user-images.githubusercontent.com/6993072/29820653-e5325b9e-8ccd-11e7-95e8-0a5c0a7333aa.png)
![image](https://user-images.githubusercontent.com/6993072/29820674-f1d9d8f4-8ccd-11e7-8d49-6eb3c6870a8f.png)

--------------

I use the latest "version" (commit 8dc0738)
also I use ffmpeg-full version with MPV-full(-git) ...currently...but this was "broken" before I switched to the git version...I also tried the basic mpv (0.26) version from the repos and it's the same thing.

-----------

system spec:

```
inxi -b
System:    Host: arch-anywhere Kernel: 4.12.9-2-ck-skylake x86_64 (64 bit) Desktop: KDE Plasma 5.10.5
           Distro: Arch Linux
Machine:   Device: desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x UEFI: American Megatrends v: 2003 date: 09/19/2016
CPU:       Quad core Intel Core i5-6600K (-MCP-) speed/max: 4399/4400 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 version: 4.5.0 NVIDIA 384.59
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e
Drives:    HDD Total Size: 12114.3GB (95.3% used)
Info:      Processes: 305 Uptime: 8:04 Memory: 4290.9/15966.7MB Client: Shell (bash) inxi: 2.3.27
```

------

PS. if you are interested: ["Sailfish OS for Sony Xperia X to be available next month, won't be cheap"](https://www.phonearena.com/news/Sailfish-OS-for-Sony-Xperia-X-officially-launched-but-youll-have-to-pay-for-it_id97436) ...even Sony Mobile is officially behind that project...well at least with helping Jolla on the porting process

**Comment by cmdrkotori** [comment]
The disabled settings are not implemented yet.

**Comment by ahjolinna** [comment]
@cmdrkotori : I remember some of them working...at least MPRIS...or is my memory completely fucked up, wouldn't be the first time (after my first epilepsy attack destroyed part of my memory...few years ago)

**Comment by cmdrkotori** [comment]
tbh epilepsy on my part is partly to blame for the lack of progress. As for MPRIS, my sister was complaining about her media buttons not working with it like the other players she uses, so maybe soon.

**Comment by ahjolinna** [comment]
Fascinating, we both have epilepsy... Okay mine "started" 5 years ago, it was fun to celebrate my birthday in the hospital for 2 weeks, because of severe kidney and liver failure, caused by the attacks massive muscle damage/death... It took me 2 months to notice my partial memory loss 

This happened 3 months before I graduated and got my diploma in computer science 

Has been hard to find a proper job after this....."C'est la vie"

**Comment by cmdrkotori** [comment]
Eight years ago I had an adverse reaction to medicine and went psychotic. (lost touch with reality.) I was in hospital for about a week or so. Several months to several years later, I'm partly but not fully recovered and it feels like I'm in a similuation, because external events seem to react to internal stimuli. But look on the bright side, usually people have to pay drug lords to get this experience.

Unfortunately Mpris support is around 600 lines sitting in at branch on my computer and will likely miss the 17.09 window for a new feature. I expect it to get merged afterwards. I have some basic testing of the windows version to do and might get it out later today if everything goes well. Appimage maybe in 17.10 or later.

**Comment by ahjolinna** [comment]
> I had an adverse reaction to medicine and went psychotic.
been there...kinda, I had those'ish problems with my new/first "round" of meds...that costed almost 600€ (which is bigger than my rent) ...at least I was smart enough to stop to take them before I went insane...Okay 3months after that I 2nd attack and dislocated my shoulder (now its broken).
Now I have way cheaper meds ("surprise" "surprise") that actually works

about the "Mpris support", I really don't care when it arrives as I use the git version (praise arch/aur simpleness), okay distro maintainers do..as they don't like to use git versions.

**Comment by kah0922** [comment]
> okay distro maintainers do..as they don't like to use git versions.

If you use the OBS, you make make packages based on the git version, like I did [here](https://build.opensuse.org/package/show/home:kah0922/mpc-qt).

**Comment by ahjolinna** [comment]
> If you use the OBS, you make make packages based on the git version, like I did here.

yes many do know OBS (I also had few pkgs there), in general speaking its really nice (at least the idea), its a good place to have many different maintained pkgs, there are some problems with it...one of them is lack of documentation, for beginners it has really bad/hard learning curve with how to do some of the more "advance" stuff...best part is that the communities (&creator/maintainers) reaction to this is usually just look at what others have done and figure it out from there...aka we don't bother to create documentation to explain stuff.

anyway, its nice that there is now a version releases (for windows) so distros wont have problem with adding it to their repos. This is just a general policy decision from distro maintainers that they don't want to add git version to their official repos, why? because its a hassle to maintain those.

**Comment by cmdrkotori** [comment]
>about the "Mpris support", I really don't care when it arrives as I use the git version (praise arch/aur simpleness), okay distro maintainers do..as they don't like to use git versions.

MPRIS is now implemented in git master. 👍
