### ISSUE TITLE
Options Sidebar too narrow

### ISSUE THREAD

**Issue by drewbitt** [cmdrkotori/mpc-qt#125]
![g2849000047](https://user-images.githubusercontent.com/26885897/30161403-5095395c-939e-11e7-8c76-fedd7dc7ef1d.png)
1440p resolution, latest Windows build

**Comment by drewbitt** [comment]
wow that was the stupidest thing I ever posted

**Comment by ahjolinna** [comment]
Mpc-qt will have some redesign soon (help from a designer) ... especially the settings menu which is currently a huge mess
