### ISSUE TITLE
Save Image (ALT-I) Does Not Append the File Extension

### ISSUE THREAD

**Issue by ehea617** [cmdrkotori/mpc-qt#127]
![image](https://user-images.githubusercontent.com/12926544/30258441-7078b668-9687-11e7-81db-2636354cf313.png)
![image](https://user-images.githubusercontent.com/12926544/30258448-7f71b1f6-9687-11e7-8748-eee7009c097c.png)

Tested on version 17.09.

**Comment by cmdrkotori** [comment]
Are you sure you have file extensions visible in explorer?

**Comment by ehea617** [comment]
Yes, the file does not have any file extension saved to it.

**Comment by cmdrkotori** [comment]
Must be a windows-only bug then.

**Comment by cmdrkotori** [comment]
Right, sorry about that.
