### ISSUE TITLE
Control bar grabs keyboard focus

### ISSUE THREAD

**Issue by Frechdachs** [cmdrkotori/mpc-qt#13]
The bottom control bar that contains the GUI buttons for playback control grabs the keyboard focus after a button is clicked, meaning that pressing the left/right arrow keys afterwards switches between the GUI buttons instead of seeking backward/forward.

btw: I think the play button should toggle between play and pause, too. IIRC, that was the behaviour in mpc-hc.

**Comment by cmdrkotori** [comment]
Yes, backwards and forwards only works if the playback window is selected.  I didn't like the idea of completely overriding standard toolkit behavior, but perhaps I can make it global.

>btw: I think the play button should toggle between play and pause, too. IIRC, that was the behaviour in mpc-hc.

Hmm, that's not the case in cccp's build of mpc-hc, but I do know that it is a standard behavior for some video applications.

In any case, I should be able to enable these behaviors in a few minor changes.
