### ISSUE TITLE
`translations/mpc-qt_it.ts` is changed during build

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#130]
Building the project, `translations/mpc-qt_it.ts` is changed. It has a large number of changes like this:
```diff
-        <location filename="../main.cpp" line="96"/>
+        <location filename="../main.cpp" line="98"/>
```
I have to reset-hard the git repo after every rebuild, because it tends to conflict with upstream changes, making this mildly annoying. I don't even use italian translations.

**Comment by cmdrkotori** [comment]
Yes this has been quite a bother to me as well to be honest. I might put these translations into an external git repo.

**Comment by cmdrkotori** [comment]
Went with the simpler solution of not including line numbers.
