### ISSUE TITLE
prepare for the upcoming vulkan support on mpv

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#132]
as next [mpv release will have vulkan](https://github.com/mpv-player/mpv/commit/91f23c7067af248846420854a0dc78c26ea6e300) (on x11 & wayland) it would be nice to have an option to use it...but it seems for now only nvidia drivers are recommend (again) for vulkan (others have issues).

if you want to wait for the next "stable" release that's fine

also Qt5.10 will have vulkan support:
http://blog.qt.io/blog/2017/06/06/vulkan-support-qt-5-10-part-1/
http://blog.qt.io/blog/2017/06/16/vulkan-support-qt-5-10-part-2/
http://blog.qt.io/blog/2017/07/03/vulkan-support-qt-5-10-part-3/
(Qt 5.10 release is planned for the end of November)

**Comment by cmdrkotori** [comment]
To use vulkan we need
* vulkan-cb backend
* refactor logodrawer to provide gl and vulkan interface
* refactor mpvwidget to provide gl and vulkan interface

---

btw southern islands and sea islands can be enabled by passing `amdgpu.si_support=1 amdgpu.cik_support modprobe.blacklist=radeon` on the kernel commandline with recent kernel. I have a r9 270x which needed that and now mpv's vulkan renderer works. More info [here](https://wiki.archlinux.org/index.php/AMDGPU#Enable_Southern_Islands_.28SI.29_and_Sea_Islands_.28CIK.29_support).

**Comment by ahjolinna** [comment]
yeah the vulkan support will mean some rework, also it seems mpv's vulkan support is currently for nvidia or at least is the recommend "way" ...as it the only one that works with least issues.
When I tested it with [my mpvconf](https://github.com/ahjolinna/mpv-conf/blob/master/PKGBUILD/mpv.tar.gz) (I had to disable it), the playback was mostly fine, but I got some hiccups/stuttering at times when I did something else or/and got a notification for example ...I dont know why really.

also we really don't know yet how good the Qt5.10 vulkan support will be

if you are interested, [here is a youtube playlist](https://www.youtube.com/watch?v=gBShsljsVvo&list=PLYO7XTAX41FOFgur5xFX0o7LuZAxAKGyI) of Khronos latest Vulkan presentations

------

btw. is there a reason why you have amdgpu? budget or the opensource drivers? ...or both? ...because radeon is really not that good (in my experiance and what I keep hearing) ...its only now lately becoming good/usable, but nvidia is still getting better ..not open but better. 
I still remember few years ago when the bomi dev bought an radeon gpu so he could get bomi working better with radeon drivers....well after ~1 month he said that he gave up and sold the gpu and will never touch amd/radeon again...okay yes radeon is way better from ~2 years ago, but its still far of from nvidia. I was hoping that amd (& intel) would have better chance with vulkan but they are already playing catch up with Nvidia...which is sad.

**Comment by ahjolinna** [comment]
[Qt 5.10 Beta has been released](http://blog.qt.io/blog/2017/10/09/qt-5-10-beta-released/)  ...if you are interested to test vulkan stuff out.

"Qt 5.10 has initial Vulkan helpers/enablers, OpenGL ES 3.2 is now exposed in a cross-platform manner, Qt Network now has an OpenSSL 1.1 back-end, new additions to Qt Quick and Qt Quick Controls 2, a tech preview of a new skeletal animation system for Qt 3D, updated Qt WebEngine, emulator improvements, and a variety of other improvements for this massive toolkit.

New modules in Qt 5.10 are Qt Network Authentication for offering OAuth/OAuth2 helpers and Qt Speech for text-to-speech. Qt Remote Objects and Qt WebGL Streaming remain in technology preview form for Qt 5.10. " --[phoronix.com](https://phoronix.com/scan.php?page=news_item&px=Qt-5.10-Beta-Released)

-------

PS. Sony has made Blade Runner 2049 movie, which is a sequel to a cultclassic.
I saw it day1 (in of the best theaters in Finland) andI think  it was a masterpiece, one of the best sequels ever made. I highly recommend it to watch it on the big screen as it's such a gorgeous movie.
I haven't really seen any good hollywood movie in YEARS, as I'm really critical....so for this movie to get in my "perfect list" is really unusual...its maybe because its such an unorthodox Hollywood movie as it can be..

I have to warn that it's really long (2h 44min) and really slow paced one, which can be a huge turnoff for many...at least in USA it has been (looking at the box office).
but I think everything....I mean everything is done correctly....it's just not for everyone...and thats why its so great.

International Trailer #3 : https://youtu.be/knptEc9_eQs
A short story trailer : https://youtu.be/UgsS3nhRRzQ?t=57s
100% spoiler free review: https://www.youtube.com/watch?v=E6eRA8PnuW4
another review (will have spoilers in the end): https://youtu.be/2RjlBoONz20
poster: https://i.imgur.com/FPwpinP.jpg

(I already I pre-ordered "Blade Runner 2049 - Steelbook - 4K Ultra HD + Blu-ray"
and "Blade Runner - Final Cut - 4K Ultra HD + Blu-ray")

**Comment by cmdrkotori** [comment]
Ok thanks for that update. I hope ubuntu switches to Qt 5.10 by the next lts or else it's going to make deploying this a lot harder. I don't want to eat the appimage fruit if I can help it.

----

>I haven't really seen any good hollywood movie in YEARS

Likewise, I find most romance themes from hollywood incredibly forced and tacky. Sci-fi flicks tend to be the only things I'll watch.

**Comment by ahjolinna** [comment]
well when it comes to ubuntu and their LTS releases its really hit and miss....as Qt5.9 is their latest LTS release, it's more likely that ubuntu will go with 5.9 because of that, but ubuntu being ubuntu and logic never seems to be part of their ...well...anything....so time will tell

but at least mpc-qt doesn't seem to require that many qt5 dependencies..so appimage or like shouldn't get that bloated.

-----

I don't know if you know this but many scifi animes like Ghost in the shell, Cowboy Bebop and Ergo Proxy at least have been [heavily influenced by the Blade Runner [](movie](http://www.animenewsnetwork.com/feature/2017-10-06/blade-runner-unbelievable-influence-on-anime/.122391).)
Also the a Blade Runner anime was made by the Cowboy Bebop director : https://www.youtube.com/watch?v=rrZk9sSgRyQ

So the orginal [Blade Runner (Final Cut)](https://www.youtube.com/watch?v=qoEyZoOTtss) and now the [sequel](https://www.youtube.com/watch?v=Xm5t3bpDcN4) are must watch movies if you are a Sci-fi fan

**Comment by cmdrkotori** [comment]
Fixed in my personal git branch, I'll push it beginning of next month as it's not an insignificant refactor.

I'm hoping to get native window embedding working too but no guarantees of course.

**Comment by ahjolinna** [comment]
that's nice hear, and maybe its for the better that you will keep that feature away until qt5.10 has been released (30.11.2017)...I can already see all the complaints :D 
anyways, have you tested how well it runs compare to OpenGL? 

also if you are interested[ here is a huge list](https://github.com/vinjn/awesome-vulkan) of all things vulkan (doc, libs, tools, sdk, etc.)

-----------------------------

on to other thing that has make me glad; is that mpv (-git) is already supporting [nvdec (& CUVID) hwaccel](https://github.com/mpv-player/mpv/commit/6b745769b1fd15ba03edad3fe381abb745bf9907) but to use it you will need the git version of ffmpeg as that feature wasn't merged to ffmpeg 3.4 release....which makes me sad.

PS. there is now mpv's own "fork/snapshot" of ffmpeg: https://github.com/mpv-player/ffmpeg-mpv

**Comment by cmdrkotori** [comment]
>that's nice hear, and maybe its for the better that you will keep that feature away until qt5.10 has been released (30.11.2017)...I can already see all the complaints :D

The problem I think will be that Qt 5.10 will not be in any of the mainstream repos, and it will have to hide behind an `#ifdef` for quite some time. It is doubtful that the next ubuntu lts would go for non-lts Qt for example, which will delay desktop vulkan for another two years.

>also if you are interested here is a huge list of all things vulkan (doc, libs, tools, sdk, etc.)

Thank you. However, looking at https://doc-snapshots.qt.io/qt5-dev/qtgui-hellovulkantexture-hellovulkantexture-cpp.html, it seems rather a lot of code to simply display a texture for my logo, (I am very lazy,) so I may work out how to get mpv to display my logo without affecting PlaybackManager rather than doing it myself when mpv is idle. I suspect I may encounter a race condition from loading files very quickly. The advantage however is that it'll work with an embedded window rather than just vulkan-cb and opengl-cb.

>PS. there is now mpv's own "fork/snapshot" of ffmpeg: https://github.com/mpv-player/ffmpeg-mpv

imo, this wasn't a good idea

* there's a one-liner patch that fixes the EOF issue
* no one should be compiling mpv with older ffmpeg versions
* no one should be compiling older mpv with newer ffmpeg versions
* forks dont work unless the fork has the manpower to match the sidestream development
* very few package managers will switch to mpv's version when the rest of the open source ecosystem is using ffmpeg-master

but enough of biting the hand that feeds me, there's probably more to it than that.

**Comment by ahjolinna** [comment]
yeah I agree that the vulkan support should be optional, would it be possible that you could add a build argument for enable/disable it ...like a [configure](https://www.gnu.org/prep/standards/html_node/Configuration.html) file 

about the ffmpeg thing, yeah I agree that mpv move is...well...kinda childish (its the old [libav vs ffmpeg war](http://blog.pkh.me/p/13-the-ffmpeg-libav-situation.html) ).
Apparently the next ffmpeg release will be a major one...and that usually means changes and breaking stuff ...apparently, I look most forward on their upcoming hwdec features (the [amd side](https://ffmpeg.org/pipermail/ffmpeg-devel/2017-October/218822.html), and [nvidia/cuvid](https://ffmpeg.org/pipermail/ffmpeg-devel/2017-October/217244.html) )

---------

PS. today was PlayStation PGW conference, and they showed a lot of nice trailers...I can't remember how much of gamer you are or if you even have a PS4(pro) ...but there you go:

- [Detroit: Become Human | PGW 2017 Trailer | PS4](https://www.youtube.com/watch?v=x-rZox_tFhM)
- [Marvel’s Spider-Man | PGW 2017 Trailer | PS4](https://www.youtube.com/watch?v=vPJm_R23g1M)
- [Shadow of the Colossus (remake) | PGW 2017 Trailer | PS4](https://www.youtube.com/watch?v=D3VG_aN2_5k)
- [Erica | PGW 2017 Reveal Trailer | PS4](https://www.youtube.com/watch?v=sYC8DAWK-Rk)
- [God of War | PGW 2017 Combat Trailer | PS4](https://www.youtube.com/watch?v=B8Cgxy9JzkA)
- [Ghost of Tsushima | PGW 2017 Reveal Trailer | PS4](https://www.youtube.com/watch?v=ctlCwPg79dU)
- [The Last of Us Part II | PGW 2017 Trailer | PS4 Pro](https://www.youtube.com/watch?v=a_FjhwD_tHQ)
