### ISSUE TITLE
Provide ways to verify the binary integrity (Checksum + GPG)

### ISSUE THREAD

**Issue by beerisgood** [cmdrkotori/mpc-qt#133]
Please provide checksum (SHA2-512 and/ or SHA3) and GPG signature with your GPG fingerprint too.
With that we can secure check if the files are fine and realy from you

**Comment by cmdrkotori** [comment]
Add checksumming but not binary signing. Perhaps later.

**Comment by beerisgood** [comment]
Sounds good!
Thanks for solve checksum problem
