### ISSUE TITLE
Settings Not Being Saved.

### ISSUE THREAD

**Issue by BlueScreenBuddy** [cmdrkotori/mpc-qt#137]
Curious if this is something I need to do manually through a configuration file or should the player automatically make one? Folder is empty and none of the settings are being saved.

**Comment by fagoatse** [comment]
Confirmed on windows(haven't tried linux yet). Apparently an mpc-qt folder is created in %appdata% but it's empty.

**Comment by cmdrkotori** [comment]
Hmm yeah, I changed how the config folder location is generated into a slightly more elegant solution. I'll have a look at it tonight.

**Comment by BlueScreenBuddy** [comment]
Awesome! Thank you very much!

**Comment by cmdrkotori** [comment]
Since this is a breaking bug, a fixed build is on the latest release as a hotfix. Replace the old exe with the new one.
