### ISSUE TITLE
Opening Video File with Resolution Larger than Screen Resolution Causes Titlebar to be Cut Off on Windows

### ISSUE THREAD

**Issue by ehea617** [cmdrkotori/mpc-qt#138]
If my monitor is 1360x768 and the video file I open is 1920x1080, the titlebar will be cut off by the top of the screen.
![image](https://user-images.githubusercontent.com/12926544/31420685-0f5e2f88-ae11-11e7-9655-58082b902e0b.png)

**Comment by cmdrkotori** [comment]
This is because mpc-qt uses the client-side geometry to calculate desired window size, and asks the system accordingly. Frame geometry is a bit harder to consistently calculate unless you resort to drawing the window decos yourself... but I'll see what I can do.

**Comment by cmdrkotori** [comment]
Right, I've stopped the crash but I have been unable to get svp working with mpc-qt. I presume I'm doing something wrong somewhere. I may just rip out the psuedo-mpv ipc interface and use mpv's with a big warning inside ipc.md to not do anything stupid.
