### ISSUE TITLE
17.10 crashes on start when SVP is running

### ISSUE THREAD

**Issue by chainikdn** [cmdrkotori/mpc-qt#140]
1. IPC connection to cmdrkotori.mpc-qt.mpv
2. { "command": ["get_property", "path"] }
3. crash!

17.9 works well

**Comment by cmdrkotori** [comment]
The fault is in ipcjson.cpp at line 81. The function should at least look like this:
```
void JsonServer::server_newConnection()
{
    QLocalSocket *connection = server->nextPendingConnection();
    if (connection)
        emit newConnection(connection);
}
```
I have no idea why it's sending me a signal when the pending connection is null (i.e. there was no pending connection??). However it's lateish (23:31) so I might have a deeper look at this tomorrow.

**Comment by cmdrkotori** [comment]
Right, I've stopped the crash but I have been unable to get svp working with mpc-qt. I presume I'm doing something wrong somewhere. I may just rip out the psuedo-mpv ipc interface and use mpv's with a big warning inside ipc.md to not do anything stupid.

**Comment by chainikdn** [comment]
It doesn't work because you invoke MpvServer::listen() TWO times:
1. in MpvServer::MpvServer() // <=== need to remove this one
2. in Flow::init()
