### ISSUE TITLE
Build errors on Windows 10

### ISSUE THREAD

**Issue by dohisev** [cmdrkotori/mpc-qt#141]
I downloaded the mpv builds `srsfckn` and I'm using `Qt 5.9.2 MSVC2015 64bit`, I did everything right but when trying to compile I'm getting this error:

```
qdrawnslider.h:96: error: C2864: 'QMediaSlider::noLoopArea': a static data member with an in-class initializer must have non-volatile const integral type
```

In this line (`qdrawslider.h`):

`static constexpr QRectF noLoopArea = { -1, -1, 0, 0 };`

What is happening?

**Comment by cmdrkotori** [comment]
Does it work if you change that line to:
`static constexpr const QRectF noLoopArea = { -1, -1, 0, 0 };`

**Comment by cmdrkotori** [comment]
btw, one reason why I don't compile with MSVC regularly at all is because my net connection isn't all that good and it takes forever to install.

Also you might have a bit of problems with MSVC Qt, because it doesn't use desktop gl.

**Comment by dohisev** [comment]
It doesn't solve unfortunately. How fast is your connection? Here is like 5Mb/s and yes, slow as hell but I managed to install MSVC 2015, it took a while but I did it only once, no need to update or anything after.

**Comment by cmdrkotori** [comment]
Just change that line to `QRectF noLoopArea = { -1, -1, 0, 0 };`. In an ideal world noLoopArea is a static variable that doesn't change and it can be optimized away... but a regular variable should be sufficient to get a build for you up and running.

IIRC, my internet is about 8 mega**bits** and VC2013 took all day to install.

**Comment by dohisev** [comment]
I don't know if I did something wrong but I downloaded the build and put everything in the right folders, these are the files:

![files](https://user-images.githubusercontent.com/32794470/31575733-a16b3cf4-b0c3-11e7-95d6-38060cec8a45.png)

and having this error:

`:-1: error: LNK1104: cannot open file 'libmpv.lib'`

**Comment by dohisev** [comment]
I realized that it won't compile using MSVC, I had to install the mingw version that comes with Qt... but it's only 32bit, how to compile to 64? Or it won't be a problem having only a 32bit version compiled?

**Comment by cmdrkotori** [comment]
:)

It should work with the 32bit framework too, use the 32bit libmpv instead.

**Comment by cmdrkotori** [comment]
Btw, from the mpv docs folder:

>Linking libmpv with MSVC programs
>---------------------------------

>You can build C++ programs in Visual Studio and link them with libmpv. To do
this, you need a Visual Studio which supports ``stdint.h`` (recent ones do),
and you need to create a import library for the mpv DLL:

```bash
lib /def:mpv.def /name:mpv-1.dll /out:mpv.lib /MACHINE:X64
```

>The string in the ``/name:`` parameter must match the filename of the DLL (this
is simply the filename the MSVC linker will use). The ``mpv.def`` can be
retrieved from the mpv build directory, or can be produced by MingGW's
gendef.exe helper from the mpv DLL.

>Static linking is not possible.

**Comment by dohisev** [comment]
I had to compile myself from the source using NSYS2 and use the `lib` from MSVC to create the library from the dll, the only problem now that I can't figure out is that when I create the x86 version I can't run the application in debug mode, only in x64, I don't know if it's because I'm in a 64bit operating system or anything else.

**Comment by wangwenx190** [comment]
@dohisev Maybe you could use my repo: https://github.com/wangwenx190/libmpv-SDK
