### ISSUE TITLE
Video won't play without working audio device

### ISSUE THREAD

**Issue by yiping-huang** [cmdrkotori/mpc-qt#144]
Alsa still has no driver for my sound card.
When I open a video file, the status bar shows Buffering, Playing then Stopped.
However, mpv plays fine.

**Comment by cmdrkotori** [comment]
mpv issue.

Also may I direct you to these:
https://www.amazon.com/gp/product/B00JLREDZG
https://www.amazon.com/gp/product/B00M3UWE3Q
