### ISSUE TITLE
big size options window

### ISSUE THREAD

**Issue by behroozramezani** [cmdrkotori/mpc-qt#145]
Hi 
I'm using Plasma 5.11 in arch Linux and i have an issue with  Ok and Apply and Cancle Button hide back 
Panel.
![screenshot_20171023_004038](https://user-images.githubusercontent.com/17659342/31866310-dd38262a-b78a-11e7-80e3-5ff33ba317f7.png)

**Comment by cmdrkotori** [comment]
Un-maximize the window. The buttons are hidden by the taskbar so perhaps "Windows can go below" needs to be switched off.
