### ISSUE TITLE
Zoom function error?

### ISSUE THREAD

**Issue by Ilya87** [cmdrkotori/mpc-qt#146]
My OS is Arch Linux x86_64. Qt 5.9.2
There is an option in View -> Zoom called "Disable snapping". What this option is intended to be? In Linux it does **nothing** with zoom and window. At least I couldn't find what this option should do.

**Comment by cmdrkotori** [comment]
Disable snapping turns off the autozoom code when the video stream size changes.

To determine its behavior:
* Set 100% zoom
* Resize to window to strange dimension
* Open 720p video
* Observe window changing to accommodate video
* Set disable snapping
* Resize window to strange dimension
* Open a different video
* Observe window keeping the strange dimension

One of the use cases of this for instance would be shrinking the video vertically as much as possible, and turning off zooming while playing a bunch of audio tracks.

**Comment by Ilya87** [comment]
In this case IMO it would be right to have a tick in front this option.
