### ISSUE TITLE
Much higher CPU usage compared to MPC-HC, both w/ HW accel

### ISSUE THREAD

**Issue by aluo-x** [cmdrkotori/mpc-qt#147]
CPU used: Kaby Lake i7-7700HQ
Drivers: 4815
OS: Win 10 FCU

Haven't had time to dig, but playing Big Buck Bunny 4K HEVC w/ MPC-HC on default settings consumes less than 10% CPU according to the Task Manager. MPC-QT uses more than 25%, and shows slightly lower GPU usage. (mid 50s compared to mid 70s)

**Comment by adamkex** [comment]
Are you using hardware acceleration/decoding?

![image](https://user-images.githubusercontent.com/9314405/32402883-e175bf52-c12d-11e7-9691-285d2c7ea4ee.png)

**Comment by aluo-x** [comment]
Even after enabling hardware decoding, and seeing the GPU decoder being used, MPC-QT still continues to have much higher CPU usage. IMO this is most definitely a bug.

**Comment by cmdrkotori** [comment]
> IMO this is most definitely a bug.

The alternative right now is worse. I believe the cause of the slowdown is redrawing the timeline and the time in the statusbar. I sped them up way back when but later ran into a few regressions with the code (#64), so I reverted at least part of it iirc. The current method is more reliable but slightly more expensive. I personally think the current state is an acceptable compromise between these two, but probably not the most desirable condition to have.  Saving the components as bitmaps and blitting should be faster, but I've been putting it off.

Perhaps in my abundance of free time I'll have another look at this. That's anywhere from two weeks time to the end of the month btw.

**Comment by cmdrkotori** [comment]
Reopening, faster gui might be nice I guess.

**Comment by Ilya87** [comment]
Arch Linux, Nvidia GeForce GTX 560. Intel Core i5-2500 3.3 GHz. 1080p30fps H.264 - About 6% cpu load. Stays the same (or few % higher) when moving window while playing.
The question to @aluo-x: 
1 - what is your videocard?
2 - Put all ticks in front of hw codecs list AND put in front of all then.
3 - After checking all codecs, try manually select each hw decoding backend and write the results (cpu usage) here.

**Comment by aluo-x** [comment]
Slightly busy this week, I'll try and look into this issue more in depth soon.
