### ISSUE TITLE
OSD doesn't work (or isn't implemented in Windows build)

### ISSUE THREAD

**Issue by adamkex** [cmdrkotori/mpc-qt#148]
I can't access the OSD in Windows 10 in v17.11. stats.lua is present in %appdata%/mpc-qt/scripts.

![image](https://user-images.githubusercontent.com/9314405/32402873-96c9f13a-c12d-11e7-9a1c-bcc995ce6d44.png)

**Comment by cmdrkotori** [comment]
Hmm yes that's a bug. Tbh I don't test the Windows build all that much, if at all.

Does it work if stats.lua is in `C:/exefolder/scripts`?

**Comment by adamkex** [comment]
Yes that works

**Comment by Ilya87** [comment]
Another comment about OSD. General Statistics and Frame Timings options have no difference (Arch Linux).

**Comment by cmdrkotori** [comment]
Yeah, I'm aware of the second page not working. Not sure what's causing that because the code looks correct.

**Comment by cmdrkotori** [comment]
Anyway, closing this because it was a problem with the client setup.
