### ISSUE TITLE
More modern UI

### ISSUE THREAD

**Issue by adamkex** [cmdrkotori/mpc-qt#150]
This would obviously be a long term goal but the current UI is based off a 20 year old design. Here are some examples of how other players look like.

Bomi:
![image](https://user-images.githubusercontent.com/9314405/32409958-c04308b0-c1b6-11e7-9efe-f402944f7d3f.png)

Baka MPlayer: 
![image](https://user-images.githubusercontent.com/9314405/32409964-d9775f98-c1b6-11e7-963b-5ac157a9611e.png) 
![image](https://user-images.githubusercontent.com/9314405/32409967-e190761a-c1b6-11e7-978a-a4cce1141d8b.png)

VLC: 
![image](https://user-images.githubusercontent.com/9314405/32409968-e81834be-c1b6-11e7-8f78-9dd22b7445d2.png)

MPC-BE: 
![image](https://user-images.githubusercontent.com/9314405/32409970-f2e15bdc-c1b6-11e7-8bcc-eac051a69278.png)

 Of course, what looks good and what doesn't is very subjective.

**Comment by cmdrkotori** [comment]
Radical changes aren't going to happen. That said, at one stage mpc-qt looked a lot like mpc-be so it is definitely possible to rice it like that. Perhaps when I add custom stylesheets to the options box.
