### ISSUE TITLE
Superfluous translatable strings

### ISSUE THREAD

**Issue by Ilya87** [cmdrkotori/mpc-qt#152]
There are many strings in the code that are marked for translation, but they shouldn't. For example codecs names, special symbols, numbers, percentages.
Also key combinations translatable strings should taken from settings. Now they are fixed.

**Comment by cmdrkotori** [comment]
Right, I think I've got just about everything. (I do know of a superfluous "1" in the settingswindow that I can't track down... I have been over it three times so far.)
Feel free to let me know if/when I missed something.
