### ISSUE TITLE
Open File with Tab

### ISSUE THREAD

**Issue by drewbitt** [cmdrkotori/mpc-qt#155]
Using keyboard only (Windows), Ctrl+O brings up Open File but if I press tab to have the ... button active (browse for files), pressing the Enter key does not bring up the browse for file window. This prevents keyboard only usage.

**Comment by cmdrkotori** [comment]
Press space.

Enter activates the default button, which is Ok.

**Comment by drewbitt** [comment]
You're right. I had been watching things with mpc-qt on one monitor with the other turned off and space opens the dialog on my second monitor, which I didn't see. My bad. No issue here.
