### ISSUE TITLE
Compilation instructions somewhat vague

### ISSUE THREAD

**Issue by emk2203** [cmdrkotori/mpc-qt#158]
At least on the new Ubuntu 18.04LTS Bionic, for successful compilation, you need to install not only `qtcreator`, but also `qt5-default` and `libqt5x11extras5-dev` for successful compilation. You can install `libmpv-dev` from standard Ubuntu repo since it is already on version 0.27.

Maybe it is worth updating the instructions, since this will be the upcoming LTS version and therefore quite popular.

**Comment by cmdrkotori** [comment]
Fixed, only took about a month. (thank you, crippling depression.)
