### ISSUE TITLE
Many options are disabled on Windows 10 platform

### ISSUE THREAD

**Issue by wangwenx190** [cmdrkotori/mpc-qt#159]
![01](https://user-images.githubusercontent.com/17877450/34339778-abbc823e-e9b3-11e7-9f33-52a14f63eb03.PNG)
![02](https://user-images.githubusercontent.com/17877450/34339781-b1f68ef6-e9b3-11e7-8593-e3861bb49eed.PNG)
![03](https://user-images.githubusercontent.com/17877450/34339782-b7f3efce-e9b3-11e7-8a1d-b7ea46c59562.PNG)
![04](https://user-images.githubusercontent.com/17877450/34339783-bbefd2aa-e9b3-11e7-892f-34626edd9a85.PNG)
![05](https://user-images.githubusercontent.com/17877450/34339785-be7e6860-e9b3-11e7-90dd-3de384deac9c.PNG)
![06](https://user-images.githubusercontent.com/17877450/34339786-c2299da4-e9b3-11e7-880f-3f3276c643cc.PNG)
![07](https://user-images.githubusercontent.com/17877450/34339788-c5147516-e9b3-11e7-97b2-8194337a4750.PNG)
![08](https://user-images.githubusercontent.com/17877450/34339789-c7bb8494-e9b3-11e7-943c-1ffaa99d0260.PNG)

# Why are these options disabled? Unfinished?   
# My platform: Windows 10 1709 x64   
# mpc-qt version: v17.11 (8f12155)

**Comment by cmdrkotori** [comment]
Yes it's unfinished.
