### ISSUE TITLE
Odd behavior with YouTube playlist links?

### ISSUE THREAD

**Issue by BobbyWibowo** [cmdrkotori/mpc-qt#162]
![screenshot_20180211_022502](https://user-images.githubusercontent.com/9364930/36065837-096bea20-0ed3-11e8-91b6-0cf502b4bd1e.png)
After adding a YouTube playlist link with the Open Network Stream option, it seemed to be adding YTDL links to all of the videos in the playlist, but unfortunately MPC-QT couldn't understand them or something? It just scrolled through all the links slowly but never played any of them. I'm not really sure, this was the first time I tried using playlist link.

I tried using mpv and it worked fine though:
```bash
mpv "https://www.youtube.com/playlist?list=PL5i2fwCJ84jjM4y2YVdIRCjzWPeIN6MzY"
Playing: https://www.youtube.com/playlist?list=PL5i2fwCJ84jjM4y2YVdIRCjzWPeIN6MzY

Playing: ytdl://AwcAK8UJL54
 (+) Video --vid=1 (*) (vp9 1920x1080 50.000fps)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus 2ch 48000Hz) (external)
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: ...
```

**Comment by BobbyWibowo** [comment]
It kept on throwing this in the terminal:
```bash
"[stream] error: No protocol handler found to open URL ytdl://awcak8ujl54\n"
"[stream] error: The protocol is either unsupported, or was disabled at compile-time.\n"
"[stream] error: No protocol handler found to open URL ytdl://gu2gkfa0j-g\n"
"[stream] error: The protocol is either unsupported, or was disabled at compile-time.\n"
```
so yeah.. Was that intentional or was there any other extra steps that I had to take to make it support the protocol?

**Comment by cmdrkotori** [comment]
Works for me fam.

![screenshot_20180211_234337](https://user-images.githubusercontent.com/11322485/36073989-1f2644c0-0f85-11e8-8a5f-8a75b8d4b68a.png)

This is with git master everything and youtube-dl version 2018.02.08, so first of all I'd suggest grabbing a newer copy of youtube-dl.

**Comment by BobbyWibowo** [comment]
Yey, works fine from here too after switching ffmpeg and mpv to master as well as upgrading youtube-dl. Though I can't be sure whether both steps or only upgrading youtube-dl were required. Previously I used release branch for both ffmpeg and mpv since SVP would, for some reason, froze mpc-qt a few milliseconds before any videos ended. Anyways, thanks~
