### ISSUE TITLE
Color Banding On Wayland

### ISSUE THREAD

**Issue by kah0922** [cmdrkotori/mpc-qt#164]
When using mpc-qt on wayland, the output looks like this:
![Shot](https://imgpile.com/images/nzsBAh.png)
When using another player or using mpc-qt's screenshot feature, it looks like this:
![Shot2](https://imgpile.com/images/nzs0Ia.jpg)

This only happens on Wayland, and only with mpc-qt.

**Comment by cmdrkotori** [comment]
mpv up until very recently would screenshot the output of the decoder. mpv is changing to use the output of the gl renderer, so this might change in the future.

Several fixes you could try:
* ensure deband is on
* ensure dithering is on
* use a rgb16f buffer
* lower dithering to 6

**Comment by cmdrkotori** [comment]
Reproduced on wayland. Lower the dither depth to 5. It's using a 16bit color mode with 5/6/5 bitdepth rgb channels. Not our bug.

If I discover a way to fix this I'll let you know.

**Comment by cmdrkotori** [comment]
Fixed in master.
