### ISSUE TITLE
new minor release for windows?

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#168]
I was thinking maybe it would be a good time to release a new version for windows users? yes there hasn't been any changes for mpc-qt itself but mpv, ffmpeg and Qt5 have had few releases that do have many fixes/changes for example[ Qt 5.10.1 has more than 300 bug fixes](http://blog.qt.io/blog/2018/02/13/qt-5-10-1-released/)

----------------

PS. if you are interested; Jolla announced at MWC [SailfishOS v3](https://jolla.com/sailfish3/) and expanding to new devices like Sony Xperia XA2*, Gemini PDA and also [4G feature phones.](https://techcrunch.com/2018/02/26/sailfish-v3-sets-its-sights-on-4g-feature-phones/)

here is an Hands on video of the v3 with the new devices : https://youtu.be/HnnngoFtrSQ

*the XA2 is follow-up to the [SailfishX project](https://jolla.com/sailfishx/) that is done together with Sony, which was [launched with the basic Xperia X model](https://blog.jolla.com/sailfishx/) ...which I have been using from the day1 and it works really well, oc there are some features missing like the fingerprint sensor support but those will come in v3 update

**Comment by cmdrkotori** [comment]
Sure. I was mulling making another release before breaking api compatibility for the next mpv anyway.

**Comment by cmdrkotori** [comment]
Fixed in the release page.
