### ISSUE TITLE
Skip forward / Skip backward - For the contents of a folder

### ISSUE THREAD

**Issue by Jordem** [cmdrkotori/mpc-qt#173]
Hello.

When you have a folder with multiple mp3 files for instance, and you open just one file, you can't jump to the next file found in the folder where the opened mp3 file is using "Skip forward".

Currently mpc-qt jumps forward/backward for it's playlist entries, mpc-hc allowed to jump in the folder by file.

Could you maybe make some option to allow mpc-qt to behave either "playlist" or "file" - wise?

Thank you.

**Comment by cmdrkotori** [comment]
>Could you maybe make some option to allow mpc-qt to behave either "playlist" or "file" - wise?

I should at least be able to implement looking for a next file in the folder when the playlist has only one entry in it. I'll have a look into mpc-hc's behavior for this soonish.

**Comment by Jordem** [comment]
To make it file-based when there is just one playlist entry is genius and simple. :)

**Comment by cmdrkotori** [comment]
Fixed. Playlist looping still not implemented though so it'll stop before the first and after the last item.
