### ISSUE TITLE
Finer speed step

### ISSUE THREAD

**Issue by Kilo19** [cmdrkotori/mpc-qt#175]
The speed step option does not seem to be in effect. Increase/decrease rate always go by a factor of 100%/50%. I wanted the default mpv behavior, where it goes up/down by 10% of the previous rate.

**Comment by cmdrkotori** [comment]
Change it here.
![screenshot_20180320_182408](https://user-images.githubusercontent.com/11322485/37643342-e6f2dc7c-2c6b-11e8-8843-caa61be3168f.png)

**Comment by Kilo19** [comment]
I'm on Windows using MPC-QT 18.03. I changed that option to 1% but when I click increase rate it still goes to 200%.

**Comment by cmdrkotori** [comment]
It wasn't wired up. I must have overlooked disabling it.

The fix will be in the next version, which should be whenever mpv releases 0.29.0
