### ISSUE TITLE
Question: is there a way to run multiple MPC-QT instances?

### ISSUE THREAD

**Issue by Bananamax** [cmdrkotori/mpc-qt#176]
Hola.

Is it possible to run multiple MPC-QT instances meaning that more than 1 video at the same time is playing? 
If not is it technically not possible or why?

Thx Bananamax

**Comment by Bananamax** [comment]
God bless you already :) But how would that work in detail plz? :)
Starting the exe with the "--freestanding" extra bit doesnt work. Once the exe is started how to "delete" the instance?

**Comment by cmdrkotori** [comment]
Thank you.

It is not working because `--freestanding` isn't written yet. :)

**Comment by Bananamax** [comment]
Oh what a damn shame :( ^^

**Comment by Bananamax** [comment]
Any chance for that to happen someday? Maybe in 2025?

**Comment by cmdrkotori** [comment]
Look at the commit above you. Pass `--freestanding` to mpc-qt through the cli.
Later on I also added a desktop entry action, so you can right click the taskbar icon to open a new window. (Linux only.)
I'll get to the menu item as well in a little bit.

**Comment by Bananamax** [comment]
Ok how does that work  via the client? Do I add the stuff in the settings.json or what?

**Comment by cmdrkotori** [comment]
If you for example were able to pin it to the taskbar, right-clicking the icon will allow you to open a freestanding window.

![image](https://user-images.githubusercontent.com/11322485/41289217-689a8984-6e8c-11e8-88ae-809d4583c31e.png)

It appends `--freestanding` to the binary's argument list.

This is a quick and useful fix, especially for cli users. Implementing the multi-window option in the settings dialog requires reworking config loading in the init code, which I don't like but probably will eventually need to do. I doubt that mpc-qt's multiwindow will work exactly the same way as mpc-hc's, (secondary instances are presently forgetful about their config,) but it might be close.

**Comment by cmdrkotori** [comment]
Freestanding mode can now be entered through usual interaction if the following conditions are met
* multiwindow mode is turned on
* a second instance is started while the main instance is running

**Comment by Bananamax** [comment]
Mhh interesting sounds intriguing. Multiwindow mode though? Cant find that anywhere in options or anywhere else?!

**Comment by cmdrkotori** [comment]
Right here fam:

![image](https://user-images.githubusercontent.com/11322485/41355812-b33f1dc2-6f65-11e8-8d34-2b8c212f05aa.png)

**Comment by Bananamax** [comment]
Mhh interesting thats grayed out. So apparently the update process with these updated files didnt work then. Is a new exe or sth. necessary?

**Comment by Bananamax** [comment]
What socery is this? I've overwritten all the "updated" files the stuff is still greyed out, cant select open a new player. What is this?

**Comment by cmdrkotori** [comment]
>What is this?

I haven't released a new Windows version with this fix in it. Not sure where you're getting these "updated" files from. I'm waiting for mpv 0.29.0. "any day now".

>cant select open a new player

Am I missing something? The jumplist thingy at the moment is Linux only. When you have an updated version, you can launch a second player by clicking on the desktop icon a second time. If it detects the previous instance with the multi-win option set, it will fall through and disable saving session information.

**Comment by Bananamax** [comment]
Ah I understand so its Linux only atm? Thought those 6 changed files 13 days ago would add that new player option oki dok. Waiting then :)
