### ISSUE TITLE
Clicking the Blank Space in the UI Pauses/Unpauses Video

### ISSUE THREAD

**Issue by ehea617** [cmdrkotori/mpc-qt#177]
Clicking the video should pause and unpause playback, but clicking on the blank space in the UI should not.

**Comment by ahjolinna** [comment]
personally I don't like this feature, but I won't mind this as long as it will be optional.

why I don't like it? for example in [Orion](https://github.com/alamminsalo/orion/issues) where this feature exists I find it annoying when 1 click pauses/unpauses the playback and double-click is the fullscreen/windowed thing, so I hate this overlap/conflict. Also I think this feature is more for a touch based UIs not desktop (mouse/keyboard)
