### ISSUE TITLE
screenshots are saved with wrong bit depth

### ISSUE THREAD

**Issue by AsukaLangleyfag** [cmdrkotori/mpc-qt#183]
Issuename. Might not be an issue with current master, but is with windows build (at least on my pc). I added screenshot-high-bit-depth option in mpc-qt and it fixed it (or maybe the fact that i rebuilt it), but i'm sure this option won't be a bad one.

**Comment by cmdrkotori** [comment]
Added at the top of the export->encode page. Defaults to on.

Thanks for bringing this to my attention.
