### ISSUE TITLE
new release with ffmpeg4 +backwards compatibility

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#184]
as [ffmpeg4](http://ffmpeg.org/index.html#pr4.0) was finally released, I was wondering if you are releasing a new version for windows and linux? 

apparently ffmpeg 4.0.1 is planned to be released in 2 weeks. I don't know when the next mpv release is happening but the current 0.28.2 should be compatible. Personally I would wait for both next releases to arrive before making a new version

oc some linux users at least won't be happy about that ffmpeg4/mpv0.28+ is now required for the future releases, at least those who use distro with the conventional release model (not rolling).
Because of this fact I was wondering if you could create an LTS version for those distros which are using the older ffmpeg/mpv...or just add a build variable to make it compatible,  YES I know this is an pain in the ass to maintain but what can you do when ffmpeg keeps breaking stuff

**Comment by cmdrkotori** [comment]
Yes, the new version will be out whenever lasch0r makes a windows release. Apparently there are a few showstopper bugs left before the next mpv, so that should be soonish.

I don't think I have enough time to make an LTS version due my schedule. Besides, not all that long ago (~2 years) every mpv user had to compile their own mpv with `mpv-build`. This is not difficult for linux users.

The current situation of mpc-qt temporarily requiring git master due to new apis was rather common before I started making releases. This situation may occur again when upstream adds support for vulkan embedding, which for us is provided by QVulkanInstance et al in Qt 5.10, while Ubuntu 18.04 ship with 5.9. As the saying goes, "[it is what it is](http://tvtropes.org/pmwiki/pmwiki.php/Main/ItCantBeHelped)".

That said, I guess a recent version that was compatible with the old render api would be the "lts".

**Comment by ahjolinna** [comment]
oh yeah I forgot the whole mpv-build thing, it would be nice if it had two version of it, aka "git" and "stable" version. Anyways maybe include this info to readme when the next release is out.

Also have you thought about "snap/appimage/flatpak" version for linux which would include the correct mpv&ffmpeg (or/and mpv-build snapshot) ...oh and Qt

btw. I did recommend that instead of maintaining an separate LTS version you could justadd a build variable to choose older mpv/ffmpeg version, which would disable those features/change/fixes that are for newer version, but oc there will be features/change/fixes that can be shared. 
(I don't think you need to test the older "mpv version code", it would be more up to the community to report the problems)

**Comment by cmdrkotori** [comment]
I've thought about an appimage, yes. In fact the install code in the project file came from an appimage tutorial. I think I've covered all the bases (there might be a few funny path-related things in the codebase that need fixing though), so the only remaining obstacle is laziness. One of these days I'll get around to running an appimage maker tool on this and see what I get.

**Comment by ahjolinna** [comment]
@cmdrkotori : any plans of releasing a new stable version? or are you waiting for next mpv release (does anyone know when it will happen)


-------

small side news if you care about Star Wars as much I do:

This is a BIG NEWS! Bob Iger (ceo of Disney) Wants Kathleen Kennedy (president of Lucas Film) gone, they just have problem to find a replacement as she has made Lucas Film so toxic working environment, apparently people have become really divided with a lot of infighting...etc.

Apparently Dave Filoni wants that job...like many fans do...Disney isn't sure yet. Dave Filoni has said that SJW has ruin Star Wars with their politics...so Disney knows this at least now ...finally

At least this is the first step to save Star Wars...sigh:
(why ?! ↓↓↓↓)
![last jedi milk](https://user-images.githubusercontent.com/6993072/41879865-15c120e4-78e4-11e8-9f7c-07800fff4f9f.gif)

**Comment by cmdrkotori** [comment]
I really want to release a new version soon.
However without a new release of mpv, it's going to make packaging for distro people difficult.

**Comment by ahjolinna** [comment]
yeah I know/get it....do you have any ETA for the mpv release....I mean have you heard/read anything....it seems mpv development has slowdown A LOT these past few months. I really wonder what they are waiting for, what is missing?

**Comment by cmdrkotori** [comment]
From what I can see, wm4 is taking a sabbatical.
There are a few deal-breaker bugs going in the mac builds I think.

**Comment by cmdrkotori** [comment]
Since mpv have no eta on the next version I'll be making a new release sometime next month. It will be marked as pre-release and depend on a recent version of mpv git master, or mpv 0.29.0 when it arrives.

**Comment by ahjolinna** [comment]
Will that include windows build? Or will that be postponed until 0.29

BTW you should maybe be prepared for ffmpeg3 (-distro) users to complain about the release, maybe you need to start providing "flatpak, snap or appimage" for these users.

I personally couldn't care less and think its up to the distro community to provide the pkgs, not the developer's

**Comment by ahjolinna** [comment]
@cmdrkotori : apparently a miracle has happened [0.29 has been released](https://github.com/mpv-player/mpv/releases/tag/v0.29.0)

**Comment by cmdrkotori** [comment]
Before the next release with mpv 0.29, I want to finish the device manager's Windows backend (i.e. use QAbstractNativeEventFilter or similar to catch WM_DEVICECHANGE and rescan). I'm on holiday at the moment (no windows build environment) and will be back on Saturday. Expect a new release around then, depending upon how long coding takes.

**Comment by ahjolinna** [comment]
No hurry just enjoy your time/holiday.

Anyway, what's your plan for macOS? (I don't care personally) and have you thought about releasing Linux versions/pkgs using OBS, as it supports deb & rpm based distros and also Arch... Even also appimage

**Comment by tyler274** [comment]
I'd also suggest appveyor for regular windows builds (even off the git master!)

**Comment by cmdrkotori** [comment]
Fixed in the release page.

>Anyway, what's your plan for macOS? (I don't care personally)

It should mostly work, but it's untested. Screensaver suppression and listing plugged devices are stubs. I have the image of a mac virtual machine (sitting inside my windows 10 virtual machine) that is waiting for me to have time to look at it.

> have you thought about releasing Linux versions/pkgs using OBS, as it supports deb & rpm based distros and also Arch... Even also appimage.

OBS looks pretty sweet, the spec files smell a lot like Arch's PKGBUILDs. However, I do not feel like I can afford to become a package maintainer. But I guess there is always a chance that I may use it in the future. :wink:

**Comment by ahjolinna** [comment]
There's a official spec file for openSUSE which could be modified to support Fedora and other rpm distributions, and the pkgbuild could be added for those who want to avoid using aur.

If you do that I can personally help maintain the pkgbuild and rpm/spec, as 1 use openSUSE and I own repo that I maintain for it (for 1 years) and I have like over 5 years of experience with pkgbuild... Mostly with ChakraOS

The deb and appimage I can learn.. If I care enough.

It shouldn't be that much work if you want only to provide the stable release (no git snapshots) as OBS handles the rebuilding automatically and the version handling/updating is just one click away

**Comment by ahjolinna** [comment]
Oh and welcome back, hope you're holiday went well.
