### ISSUE TITLE
Is there any way to install this in solus?

### ISSUE THREAD

**Issue by bsucker98** [cmdrkotori/mpc-qt#185]
when I followed the install instructions & tried to build the qmake+make,
I get this error,(after entering qmake)
_Project ERROR: mpv development package not found_

after googling a bit, I guessed, libmpv could be the case & I found that it's not available in the solus software center...
could you pls provide a way if can,(maybe a snap or flatpak, atleast would support in the next release)
I badly want to use this because of the playback quality it offers & shortcuts..

**Comment by ahjolinna** [comment]
@bsucker98 : my guess is that it's the same as in rpm based distros (like fedora/openSUSE) where they have splitted all/most the pkgs, aka you will need mpv-devel to build mpc-qt but libmpv only is needed to run

**Comment by ahjolinna** [comment]
PS. have you voted mpc-qt to be added to Solus official repos? : https://dev.solus-project.com/T4979

**Comment by bsucker98** [comment]
> @bsucker98 : my guess is that it's the same as in rpm based distros (like fedora/openSUSE) where they have splitted all/most the pkgs, aka you will need mpv-devel to build mpc-qt but libmpv is only needed to run
also if you want to install the latest git version of mpc-qt you need to have mpv 28.2+ with ffmpeg4/-git ...easiest way would to install mpv-build version (guide for souls)

Thnks, will give a try..

& yes, that's me, last comment (April 13th) [https://dev.solus-project.com/T4979](url)

**Comment by bsucker98** [comment]
**Note:** as there was no package called _mpv-devel_, I installed _mpv-libs-devel_.
Now qmake works fine, but others don't..

This is what I get, 

for **make -j threads**
_make: *** No rule to make target 'threads'.  Stop._

& for **sudo make install**
_lupdate-qt5 -locations none -no-ui-lines /home/bmora/src/mpc-qt/mpc-qt.pro
make: lupdate-qt5: Command not found
make: *** [Makefile:827: translations/%{QMAKE_FILE_IN}.ts] Error 127_

Also note that I enabled libmpv by installing mpv-build as in [https://github.com/mpv-player/mpv-build](url)

**Comment by cmdrkotori** [comment]
You need to type something like `make -j8` for an octo-core system.

**Comment by bsucker98** [comment]
:| got the same error,
_lupdate-qt5 -locations none -no-ui-lines /home/bmora/src/mpc-qt/mpc-qt.pro
make: lupdate-qt5: Command not found
make: *** [Makefile:827: translations/%{QMAKE_FILE_IN}.ts] Error 127_

anyway thnx.

**Comment by bsucker98** [comment]
It seems, they(solus) won't accept any more third party apps, 
see the last comment by JoshStrobl(a main developer)
[https://dev.solus-project.com/T1392](url)

**Comment by ahjolinna** [comment]
@bsucker98 : if can ask if mpc-qt could be add here: https://github.com/community-repositories-for-solus/solus-community-repo

as for why Solus won't add new "3rd-party" apps, it seems they are moving away from them by favouring  .snap pkgs instead; https://github.com/solus-project/3rd-party/ <- check readme

**Comment by ahjolinna** [comment]
PS. about that last error do you have Qt5 Linguist installed? (-devel)

**Comment by cmdrkotori** [comment]
Correct, linguist needs to be installed for `lrelease` and `lupdate`. I updated the readme as appropiate in 0236da2ca4d0e4ea9805ca2d6819b1b94ef213c0. Speaking of, I probably should update that screenshot.

**Comment by bsucker98** [comment]
Unfortunately, it seems qt5-default, libqt5x11extras5-dev, qttools5-dev-tools and libmpv-dev are not available for solus, I installed some packages with similar names, & I got a different error for 
**sudo make install**

_/usr/bin/lupdate -locations none -no-ui-lines /home/bmora/src/mpc-qt/mpc-qt.pro
Updating 'translations/mpc-qt_it.ts'...
    Found 829 source text(s) (0 new and 829 already existing)
Updating 'translations/mpc-qt_ru.ts'...
    Found 829 source text(s) (0 new and 829 already existing)
/usr/bin/lrelease translations/mpc-qt_it.ts -qm resources/translations/mpc-qt_it.qm
Updating 'resources/translations/mpc-qt_it.qm'...
    Generated 687 translation(s) (678 finished and 9 unfinished)
    Ignored 142 untranslated source text(s)
/usr/bin/lrelease translations/mpc-qt_ru.ts -qm resources/translations/mpc-qt_ru.qm
Updating 'resources/translations/mpc-qt_ru.qm'...
    Generated 387 translation(s) (382 finished and 5 unfinished)
    Ignored 442 untranslated source text(s)
g++ -c -pipe -Wall -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DMPCQT_PREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /usr/include/QtWidgets -isystem /usr/include/QtX11Extras -isystem /usr/include/QtGui -isystem /usr/include/QtNetwork -isystem /usr/include/QtDBus -isystem /usr/include/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o ipcmpris.o ipcmpris.cpp
In file included from ipcmpris.cpp:7:0:
mpvwidget.h:13:10: fatal error: mpv/render.h: No such file or directory
 #include <mpv/render.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1099: ipcmpris.o] Error 1_

**NOTE:** also ran make -j8 before make -j threads(maybe, that made the defferece & got a big output, not to mention my cpu is not octa core:p, I didn't note it)

**for make -j threads**(same)
_make: *** No rule to make target 'threads'.  Stop._

thanx

**Comment by bsucker98** [comment]
> @ahjolinna you can ask if mpc-qt could be add here: https://github.com/community-repositories-for-solus/solus-community-repo

thanx for leting me know, requested. 
Will hope it would work out.

**Comment by cmdrkotori** [comment]
@bsucker98 
For the moment you need mpv git master. Try building with mpv-build with mpv+ffmpeg master or waiting a few days for the next mpv release.

**Comment by bsucker98** [comment]
thanx
will wait for the next release. seems building with mpv-build & mpv+ffmpeg master would be hard in solus, atleast for me, I'm not a geek;)

**Comment by bsucker98** [comment]
finally Accepted For Inclusion https://dev.solus-project.com/T4979
