### ISSUE TITLE
No decoding for VOB files

### ISSUE THREAD

**Issue by Ilya87** [cmdrkotori/mpc-qt#186]
My OS - Arch x86_64, ffmpeg 4, mpv-git 7e06a4 built on Sat Apr 21 03:21:16
When I try to play vob file mpc-qt opens and shows only default window. No matter whether I use doubleclick on file to open or command line mpc-qt VTS_01_1.VOB.
.

**Comment by ahjolinna** [comment]
@Ilya87 :  can you provide a **sample file** and/or **gdb log** output?

**how to gdb**: [arch wiki link](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Gdb)
&
**how to make sample file**:
To cut down a file, open the terminal and run next command:
`dd if=path/to/original/file of=path/to/result/file bs=1024 count=10000`
_This command will produce about 10MB file which is cut from front part of the original file. The size of result file is determined as bs*count bytes. If you don't think the file size is too small, you can increase the size by adjusting these parameter._

**Comment by Ilya87** [comment]
https://yadi.sk/i/7kKxPBkc3UxGMh - made with ffmpeg -c copy command. 10 seconds. ffplay and mpv decodes without problem. GDB output without debugging symbols shows no errors. AND I FOUND THE SOURCE OF THE PROBLEM! Extension. When it is uppercase VOB - no decoding, when lowercase - play OK.
