### ISSUE TITLE
Unknown symbol "mpv_render_context_create" and failure to launch - possible newer mpv incompatibility?

### ISSUE THREAD

**Issue by Hikari-chin** [cmdrkotori/mpc-qt#188]
Hello,

I was able to compile and install mpc-qt successfully, but I receive this error on attempting to launch it: `mpc-qt: symbol lookup error: mpc-qt: undefined symbol: mpv_render_context_create`. I'm not really certain what the problem could be; there weren't any errors during compilation, mpv's render.h still references `mpv_render_context_create` so I doubt it's been changed or renamed, etc. I am on Ubuntu 18.04.

**Steps to Reproduce:**
1. **(I doubt this is related, but it's the only thing different I did from the "standard" process):** Compile and install [nv-codec-headers](https://github.com/FFmpeg/nv-codec-headers), libvulkan-dev, [SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools), and [SPIRV-Headers](https://github.com/KhronosGroup/SPIRV-Headers) for Vulkan and SPIRV support.
2. Build the latest mpv with [mpv-build](https://github.com/mpv-player/mpv-build), making sure to do `echo --enable-libmpv-shared > mpv_options` before building.
3. Built latest mpc-qt with `qmake`>`make -j8`>`sudo make install`
4. Attempt to launch mpc-qt, causing the error; mpc-qt will attempt to launch for several seconds (loading wheel by the title in the top bar) but never actually launch, then exit silently.

**Comment by cmdrkotori** [comment]
You need to run `ldconfig` as root after installing libmpv git master into `/usr/local/*`. Also `/usr/lobal/bin` should be in your path before `/usr/bin`. Something like this:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
```

**Comment by cmdrkotori** [comment]
You may get more joy resetting to an older mpc-qt release that is known to work.

For example, mpv 0.27.2 is the version in ubuntu bionic. To revert to a version that works with this, type `git reset --hard v17.11` at the command-line and compile with system libmpv instead of your own libmpv build.

This should fix your issue and anyone using the libmpv from ubuntu.
