### ISSUE TITLE
Use of deprecated hook API should be removed

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#189]
I plan to remove the old hook API after mpv 0.29 has been released. mpc-qt still seems to use the old API, which then will silently fail (the "hook-add" command will be removed). There's a new C API available, look for mpv_hook_add.

Since mpc-qt already depends on the new render API that mpv 0.29 will add, it would be a good idea to update the API use now, especially in case you care about distros.

I can make a PR to do the change myself if that is preferred.

**Comment by cmdrkotori** [comment]
No need for the PR, I'll have a look at this tomorrow.
