### ISSUE TITLE
No shuffle option for playlists ?

### ISSUE THREAD

**Issue by axbw** [cmdrkotori/mpc-qt#190]
I tried all the GUIs for mpv and finally found mpc-qt to be the acceptably decent enough to use, though I don't understand your fascination with MPC.

The only important feature missing is the shuffle playlist option, unless it was named something else in an MPC way in which case, please let me know.

Thanks.

**Comment by cmdrkotori** [comment]
The playlist functionality is modeled after clementine, xmms, qmmp, with an mpc-hc interface. Shuffle doesn't exist yet in my implementation, but may soon. This involves populating the playlist context menu with more actions. I'd like to get this done by the end of the coming week.

**Comment by axbw** [comment]
Excellent, thank you very much for that cmdrkotori. I will keep my fingers crossed.
