### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by forsomefun** [cmdrkotori/mpc-qt#191]
Is there a quick way to compile on windows been trying to figure out how that would be possible

**Comment by cmdrkotori** [comment]
run the release script from the msys2 console is what I do.

Naturally I download the libmpv.dll et al from mpv-dev first. binaries such as youtube-dl in binaries. etc.
It's all there in the shell script.

**Comment by forsomefun** [comment]
It keeps giving me error
 cp: missing destination file operand after 'mpc-qt-/libicuuc58.dll
Also it saying cp: omitting directory 'resources/translations/'

I couldn't find mpc.exe so I just took that from another release.
