### ISSUE TITLE
Windows Install 

### ISSUE THREAD

**Issue by forsomefun** [cmdrkotori/mpc-qt#192]
I am getting this error messages
It keeps giving me error
cp: missing destination file operand after 'mpc-qt-/libicuuc58.dll
This is for everything under
read -r -d '' dlls

while trying to make the .7zip

**Comment by cmdrkotori** [comment]
Qt has probably changed which libraries it needs by now.
I might have a go at making a quick and dirty shinchiro build.
Perhaps the other bug about the application icon can be fixed at the same time as well.
