### ISSUE TITLE
App's icon on Windows

### ISSUE THREAD

**Issue by redking974** [cmdrkotori/mpc-qt#193]
Hi, I don't know if it's an issue but when I pin the app on my bar it tells me that the app/exe have no icon. I got this error when I try to change the icon because Windows displays a general icon. It's the same thing if I link a file (a .mov for example) whith mpc-qt. I will get a ugly generic icon instead of the mpc-qt icon.

Regards

**Comment by cmdrkotori** [comment]
Fixing this is as simple as using a windows resource compiler and add our own `.ico` to the exe.
