### ISSUE TITLE
mpc-qt doesn't launch

### ISSUE THREAD

**Issue by sinqbad** [cmdrkotori/mpc-qt#195]
Manjaro | KDE 

Thank you for the steps to compile. It appears to compiled just fine however mpc-qt doesn't launch. It appears in application launchers and there is a bin attached to it however either launching it from the application menu or CLI doesn't load anything. 

```
mpc-qt \[Anirrent_\&_FênixSub\]_Yuru_Camp_01_v2_\[HDTV\]\[720p\]\[8bits\]\[BE4A46CE\].mkv 
Icon theme "pop-os-branding" not found.
Icon theme "ubuntu-mono-dark" not found.
Icon theme "ubuntu-mono-light" not found.
Icon theme "elementary" not found.
[glwidget] assigning x11 display
Segmentation fault (core dumped)
```

**Comment by cmdrkotori** [comment]
Hmm. Okay, I'd like to test if the new hwdec code is the cause.

Recompile and test with `git reset --hard e730a4f8570b9e3d96f0866888e21150169e50f1`
Recompile and test with `git reset --hard 913c3fe4b32820c610fb6114be7bf761e6e3c8b9`
If the second works, it means I'll need a workaround.

**Comment by ahjolinna** [comment]
also a basic [gdb](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Gdb) output may help, then there is [Valgrind](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Valgrind) that will have better out put than gdb, or then [Strace](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Strace) which should tell everything

**Comment by sinqbad** [comment]
Tried recompiling with:
`git reset --hard e730a4f8570b9e3d96f0866888e21150169e50f1`
`git reset --hard 913c3fe4b32820c610fb6114be7bf761e6e3c8b9`
Still not working.

Strace: https://pastebin.com/W5zxpbFG
valgrind: https://gist.github.com/sinqbad/98af105da20af5f5587865ea7d2d6211

**Comment by cmdrkotori** [comment]
Thanks for the valgrind info.
It appears to crash while adding a widget to a layout, probably the gl widget. This is a just a guess.
Can you recompile and dump a log with debug info? You can force the compiler to do this for a release build by adding `QMAKE_CXXFLAGS += -ggdb` to the project file.

**Comment by sinqbad** [comment]
Sorry, which file is the "project file"? `Makefile`?

**Comment by cmdrkotori** [comment]
The `mpc-qt.pro` file. It's used by qmake to generate the Makefile.
Remember the `make clean` to clear out the old build.

**Comment by sinqbad** [comment]
Thanks for being patient with me. I added the line to the project file and recompiled and what next?

**Comment by cmdrkotori** [comment]
Give me another crash dump. This time it should be slightly more detailed. :+1: 
I may be able to fix it tomorrow.

**Comment by sinqbad** [comment]
Steps:
1. Replaced line 7 to `QMAKE_CXXFLAGS += -ggdb`
2. `make clean`
3. `qmake`
4. `make thread -4`
5. `sudo make install`
6. `gdb mpc-qt` `r` https://pastebin.com/sbebQaj3
7. `valgrind --logfile=$HOME/valgrindmpcqt` https://gist.github.com/sinqbad/729275fc9c9dbd9bf1ea1a6df1b454cc

**Comment by cmdrkotori** [comment]
Thanks.

**Comment by cmdrkotori** [comment]
Okay, after another look it appears to be erroring out creating the gl context at QXcbIntegration::createPlatformOpenGLContext. Specifically a bad memory access is happening inside i965_dri.so. This is a driver bug.

**Comment by BobbyWibowo** [comment]
Cough, excuse me, is this error by any chance similar to this issue? https://paste.fiery.me/wucufacewe.log

**Comment by cmdrkotori** [comment]
Yes, that's quite similar to the log here.
