### ISSUE TITLE
qmake unsuccessful, "Project MESSAGE" outputs

### ISSUE THREAD

**Issue by kdponce** [cmdrkotori/mpc-qt#199]
xxxx@xxxxxx:~/src/mpc-qt$ ~/Qt5.11.0/5.11.0/gcc_64/bin/qmake
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!

First tried following the instructions listed in the README, same output. This one was done after installing Qt Creator 5.11 Open Source from their website. 

Since this is apparently not a bug, is it possible to suppress this output and proceed?

**Comment by cmdrkotori** [comment]
Sure. That message is only there because I'm reading the platform window handle for hardware acceleration purposes.
