### ISSUE TITLE
High CPU usage due to screen updates

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#20]
When "Status" or "Seek Bar" are checked in the view menu, playing an audio gives about 10% CPU usage, without them only about 3-4%.

I suspect the graphical updates are causing this, and it might be a good idea to throttle them (although not required).

This seems to be a common problem with the libmpv client API, and I'm wondering if there should be an opt-in mechanism to throttle certain property updates.

mpv CLI with --quiet needs only about 2-3% CPU. I suspect the additional overhead seen in mpc-qt is caused by libmpv property updates. libmpv might be doing too much just to update a single property; in the long range I'll probably do something about this.

Note that mpv CLI with video playback enabled tries to reduce OSD/terminal status updates to at most once per video frame (except for low framerate video), but this mechanism is independent from property updates.

**Comment by cmdrkotori** [comment]
>I suspect the graphical updates are causing this, and it might be a good idea to throttle them (although not required).

You're quite right. I checked and each actively updated section adds about another 3% cpu.

I suspect that the seekbar may be improved by a switch to a gl renderer or a QtQuick item. As for the stasus line, there's not much that can be done about expensive text rendering, other than doing it myself with prerendered glyphs and asking openGL to render them. I'm not quite sure if that is even reasonable to do with the infostats section however.

>Note that mpv CLI with video playback enabled tries to reduce OSD/terminal status updates to at most once per video frame (except for low framerate video), but this mechanism is independent from property updates.

To be honest, it's been on my mind to include in MpvWidget a hash map of the last recent property values. If added, it would be possible to depend more on the hash map rather than emitted events, rate limit on the video framerate as you suggest, and perform an update plus throttle reset on play/pause. I'm thinking of a 200ms backup timer to ask for gui changes for slow framerates.

>I'm wondering if there should be an opt-in mechanism to throttle certain property updates.

I suggest every x frames plus a guaranteed update of every x milliseconds, with the default being no throttling. I wouldn't have to change much in that case. That's said it's still a worthwhile endeavor for me to optimize these widgets in any case, so I'll try to fix it my end. There are likely some areas where I've been lazy anyway.

**Comment by wm4** [comment]
>I suspect that the seekbar may be improved by a switch to a gl renderer or a QtQuick item.

Interaction between QtWidget and qtquick isn't too good. It's probably not a good idea to mix them.

>As for the stasus line, there's not much that can be done about expensive text rendering, other than doing it myself with prerendered glyphs and asking openGL to render them. 

Is it really the text rendering that's so expensive?

>I suggest every x frames plus a guaranteed update of every x milliseconds, with the default being no throttling.

One could add something like this:
```C
/**
 * Rate-limit property change notifications. This can be used for user interface purposes,
 * when too frequent updates would become a performance issue, while on the other
 * hand a lower rate of updates does not worsen the user experience.
 *
 * The throttle_us parameter will restrict how soon the next change notification is sent.
 * Throttled change notifications will all batched into the next actually delivered
 * notification. Basically, if there is an update less than throttle_us after the previous
 * update, it will be delayed until throttle_us time has passed after the previous
 * update. Multiple updates within the waiting period will all be merged.
 *
 * If the call affects multiple properties, it is undefined whether the throttling applies
 * to all properties at once, or only each property individually.
 *
 * @param registered_reply_userdata ID that was passed to mpv_observe_property
 * @param throttle_us smallest duration after which a new update can come, in microseconds
 * @return negative value is an error code, 0 means success
 */
int mpv_set_property_update_rate(mpv_handle *mpv, uint64_t registered_reply_userdata,
                                 uint64_t throttle_us);
```

The "registered_reply_userdata" thing is a bit strange, but that's also what mpv_unobserve_property uses to reference properties.

Note that a cheap but effective way to achieve this for all properties without new API would be throttling calls to mpv_wait_event(), as updates to the same property are always merged into a single update and never queued.

**Comment by cmdrkotori** [comment]
Earlier today I naively implemented a separate thread for only handling events, and sleeping afterwards for 1000/15 ms. It sat on 5.3% cpu with the default widgets open, but it does not always wake up in time to tell me that I should be rendering frames, so album art is a bit iffy.

However, in the commit I just pushed we throttle the noisy properties and flush those at 1000/12 ms, which reduces cpu to an acceptable ~6.0%.

**Comment by cmdrkotori** [comment]
While I'm thinking of it, I'll add that a client api call as you described feels rather nice.

**Comment by wm4** [comment]
Unfortunately it doesn't seem to help much. mpv CLI shows ~3.3%, mpc-qt ~8.0% for the same file.

Well maybe it's not so important.

Still pondering whether I just add a rate-limiting API. One dumb thing is that if you have multiple properties that update at the same time (like playback position and A/V sync), it's still hard to fire the change events at exactly the same time, because the times might always be off by a few nanoseconds. Either a more complex implementation is needed, or some additional "tolerance" that would allow the client API to return the event slightly too early or too late. Annoying.

**Comment by cmdrkotori** [comment]
I'm afraid much of the high cpu usage was entirely my bug. Sorry about that.

>One dumb thing is that if you have multiple properties that update at the same time (like playback position and A/V sync), it's still hard to fire the change events at exactly the same time, because the times might always be off by a few nanoseconds.

Existing players seem to tolerate this, so one could conceivably pair a property change with a frame counter and/or audio counter, so that every property change event is deferred until the counter changes.
