### ISSUE TITLE
mpris artist metadata should be a list

### ISSUE THREAD

**Issue by FichteFoll** [cmdrkotori/mpc-qt#204]
According to https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#index6h4, the `xesam:artist` field (and similar fields) should be a list of strings, not a single string.

Initially reported in https://github.com/FichteFoll/discordrp-mpris/issues/6.

**Comment by FichteFoll** [comment]
Thanks for the quick fix :+1:

**Comment by FichteFoll** [comment]
I noticed that there is no `xesam:title` available when playing a video (without ID3 tag data). Otherwise this is is working nicely.

**Comment by cmdrkotori** [comment]
Fixed missing xesam:title in ef896b43317b2bec80104c60808e60ce492b1c33. Should be fine now.
