### ISSUE TITLE
Feature Request: ReClock functionality

### ISSUE THREAD

**Issue by Syst3mSh0ck** [cmdrkotori/mpc-qt#205]
I am still using MPC-HC 32-bit because ReClock is a 32-bit DirectShow Filter which replaces the Audio Renderer. After searching extensively and trying other solutions I cannot find a suitable replacement. I understand DirectShow Filters are unlikely to be implemented because MPC-QT uses VapourSynth.

Would it be possible to re-implement some of ReClock's functionality in MPC-QT's own Audio Renderer natively instead? I fear ReClock will become deprecated in the future when Microsoft move DirectShow from Deprecated to Removed in one of their Semi Annual Updates. Also it isn't ideal being stuck on 32-bit due to ReClock because x265 10-bit decoding is much faster on 64-bit.

ReClock Source Code: http://oss.redfox.bz/ReClock/

If this is possible it would be great. Thanks for your work so far!

**Comment by cmdrkotori** [comment]
>Would it be possible to re-implement some of ReClock's functionality in MPC-QT's own Audio Renderer natively instead?

Yes, this is already implemented. Under Options->Playback->Sync. Here's what the options mean:
![screenshot_20180625_113421](https://user-images.githubusercontent.com/11322485/41826318-fbdd76dc-786b-11e8-9f11-0eb7c119cd97.png)

You'll probably also want to turn on temporal interpolation in the video renderer to get madvr-like video interpolation. Or simply load the placebo preset.
