### ISSUE TITLE
Delay when exiting fullscreen

### ISSUE THREAD

**Issue by PhantomGamers** [cmdrkotori/mpc-qt#207]
I hesitate to post this as I imagine it might be an issue with my setup and not necessarily an issue with the program itself, as I would think other people would have reported this, but I figure I'll give it a shot in case  you might know what would cause this.

Basically when double clicking the window to exit fullscreen and go back to windowed mode, the player freezes the video in fullscreen for a few seconds (audio continues playing) before it properly goes back to windowed.

I've tried both the latest Windows release on Github, and I've also built it myself and have experienced the issue on both builds. This occurs both on default settings and on each of the quality presets.

My specs are as follows:
OS: Windows 10 x64 build 1803
Display: Agon AG35UCG (3440x1440 100Hz)
GPU: NVIDIA GTX 1080
CPU: AMD Ryzen 7 1800X
RAM: 32GB DDR4 @ 2933MHz

I suspect the issue might be that when the video is playing in fullscreen that it might change the refresh rate, and the delay occurs when going back to the refresh rate set by Windows, but in that case I'd think it would also freeze whilst entering fullscreen mode and yet it enters fullscreen instantly.

Also normal MPV does not have this issue on my system, it's only with MPC-QT.

EDIT: Hm, it seems to actually not freeze if I wait about 10 seconds while in fullscreen. I tend to switch back and forth frequently when I'm in the middle of a conversation so I didn't think about trying to wait. Still quite annoying though and it's not present on any other player I've tried.

**Comment by cmdrkotori** [comment]
Testing an older build from a month or so ago, the delay (around a second or so) appears to be triggered by the compositor trying to give fullscreen applications exclusive control of the monitor. I'm more of a fan of ordinary borderless fullscreen windows rather than exclusive mode.

>I suspect the issue might be that when the video is playing in fullscreen that it might change the refresh rate

We don't do that at present. Maybe one day.

**Comment by PhantomGamers** [comment]
Just to clarify then, you're saying this is a Windows issue?

> I'm more of a fan of ordinary borderless fullscreen windows rather than exclusive mode.

I agree with you here, but wouldn't this be something defined by the program?

Frankly, I don't have a complete technical understanding of how this works, but as I also prefer borderless fullscreen and I run all of my games in borderless, I have no issue with Windows trying to force exclusive mode for any other programs.
