### ISSUE TITLE
Slightly unintuitive togglePlayback behavior

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#21]
- double click something on the playlist
- use "next" command a bunch of times
- [use "togglePlayback" twice -> playback pauses and unpauses, as expected]
- use "stop" command
- use "togglePlayback" -> unexpectedly plays the original entry from the first step

This happens because the playlist selection is still on the original entry, and the "togglePlayback" command does exactly what it is documented to do.

I'm undecided whether the best way to fix this would be by changing the plalyist selection to the new entry when playback of something is started. An alternative fix would be to make "togglePlayback" always refer to the entry that is rendered in bold on the playlist.

**Comment by cmdrkotori** [comment]
>An alternative fix would be to make "togglePlayback" always refer to the entry that is rendered in bold on the playlist.

This is the approach I went with. I also changed next/previous commands to work on the item rendered in bold.

**Comment by wm4** [comment]
OK, I think the result is good.

**Comment by cmdrkotori** [comment]
Oh man, those commits are the wrong issue. Please ignore. I'm not going to rewrite history just for a typo.

**Comment by wm4** [comment]
Works great.
