### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Purarity** [cmdrkotori/mpc-qt#216]
How do i compile with qt? i have placed the folders from mpv into mpc-qt but idk how to compile it with qt, im on windows.

**Comment by cmdrkotori** [comment]
It's almost the same as on Linux.

```
qmake mpc-qt.pro
make release-clean
make -j4 release
```
See more at https://github.com/cmdrkotori/mpc-qt/blob/master/make-release-win.sh
You can also run that script and it will spit out a release-candidate zipfile that bundles with all the needed libraries.
