### ISSUE TITLE
mpv and client logging

### ISSUE THREAD

**Issue by starks** [cmdrkotori/mpc-qt#219]
Where do I enable this and where do I find the logs?

I'm one of those insane people who took the time build the git master on Windows.

**Comment by cmdrkotori** [comment]
You'll find them on the text console.
I've been meaning to create a proper UI and logging framework for quite some time.

**Comment by cmdrkotori** [comment]
Oh, I forgot. They can be switched on and off here:

![screenshot_20180805_150055](https://user-images.githubusercontent.com/11322485/43682732-724afc08-98c0-11e8-86ad-947e6e7440ca.png)

>I'm one of those insane people who took the time build the git master on Windows.

Welcome to the 1% club.

**Comment by starks** [comment]
Where can I find that text console? That's what I've been looking for.

**Comment by cmdrkotori** [comment]
Ok, just tried the MSYS2 console and powershell, they're not showing the debug console output. So on Windows it appears that you'll only get logging on the console if it's run inside the development environment, or if it's compiled with `CONFIG += console`.

I'll provide the proper fix for this (the ui) tomorrow.

**Comment by starks** [comment]
Thanks. Recompiled and confirmed.

**Comment by cmdrkotori** [comment]
Fixed in master.
