### ISSUE TITLE
Windows binaries missing qt.conf

### ISSUE THREAD

**Issue by net147** [cmdrkotori/mpc-qt#221]
I get the following message if I try to start mpc-qt.exe:

---------------------------
mpc-qt
---------------------------
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, webgl, windows.

---------------------------
OK   
---------------------------

To fix, I need to create qt.conf next to mpc-qt.exe with the following content:
> [Paths]
Prefix=.

Please add qt.conf to the Windows release packages.

**Comment by net147** [comment]
It crashes after clicking OK.

**Comment by cmdrkotori** [comment]
Manually added to the latest release.
The build script should be updated by the time of the next release.
