### ISSUE TITLE
[Feature request] Limit volume slider maximum to 100%

### ISSUE THREAD

**Issue by net147** [cmdrkotori/mpc-qt#222]
It would be nice if there was option to limit volume slider maximum to 100% so it behaves like MPC-HC.

**Comment by cmdrkotori** [comment]
You can find this option under the Tweaks page in the settings dialog.

**Comment by net147** [comment]
Thanks!

**Comment by net147** [comment]
It is still possible to get to 110% volume by scrolling mouse wheel up while mouse is over the video area.
