### ISSUE TITLE
thumbnails save on linux?

### ISSUE THREAD

**Issue by 3k2** [cmdrkotori/mpc-qt#225]
Hey

I am trying to make thumbnails from my videos like these: 
![image](https://user-images.githubusercontent.com/11908261/45110559-4bf7e180-b14b-11e8-9a60-257f232a99c6.png)

but the option on my arch linux install is greyed out? am I missing some package or something?

**Comment by cmdrkotori** [comment]
You are not missing a package; thumbnail creating hasn't been written (yet).
