### ISSUE TITLE
[question] vulkan support?

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#229]
what is the status of the Vulkan support? did you add it? I remember that you made some prep work for it. Qt 5.10+ has support for it and so does mpv (0.28+).

I really don't know if there is any real benefits (yet), but I think it would be nice to have this feature anyways (just in case)

-----
PS. also try to remember to use [clazy](https://github.com/KDE/clazy) :P 
and check out the [KDE HIG](https://hig.kde.org/)'s

btw. I'm buy Sony's next high-end phone for 800€, [Xperia XZ3](https://www.sonymobile.com/global-en/products/phones/xperia-xz3/): The phone has an (J)OLED*, 2K, HDR, 10bit-panel (certified for the BT.2020 standard)...[here is the gsm-areena review of it](https://www.gsmarena.com/sony_xperia_xz3-review-1822.php)
I'm not sure which color yet: Black, Silver White, Forest Green, Bordeaux Red

*[JOLED](https://www.oled-info.com/joled) (Japan OLED) was established in August 2014 by Japan Display, Sony and Panasonic

**Comment by cmdrkotori** [comment]
As far as I'm aware, libmpv does not expose vulkan.
