### ISSUE TITLE
Playing a smb:// URL doesn't auto-load .srt subtitle with same name

### ISSUE THREAD

**Issue by net147** [cmdrkotori/mpc-qt#232]
Playing a smb:// URL on Linux doesn't auto-load the .srt subtitle with same name in same folder.

**Comment by cmdrkotori** [comment]
Is your options dialog set to something like this?
![screenshot_20190117_222305](https://user-images.githubusercontent.com/11322485/51318627-9187cc00-1aa6-11e9-898e-8724faedc046.png)
The external file autoload logic is in mpv itself btw, so I'll have to close this.

**Comment by net147** [comment]
Yes but Path is ".;./subtitles;./subs" and Match is "Exact". It works fine if I copy the files to local before playing.

**Comment by cmdrkotori** [comment]
Yes, autoload.lua can only deal with files.
You might have more success if you mount it to the filesystem like this: https://wiki.ubuntu.com/MountWindowsSharesPermanently
