### ISSUE TITLE
Window size for anamorphic SD video in MP4 file is incorrect

### ISSUE THREAD

**Issue by nu774** [cmdrkotori/mpc-qt#233]
When I open a SD video coded with H264 720x480, PAR 6:5 in MP4, mpc-qt displays in 720x480 window.
When I open it in mpv, mpv prints a message like:
`VO: [gpu] 720x480 => 864x480 nv12`
and displays it (correctly) in 864x480 window.

This is what MediaInfo says:
```
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
```

And this is the related fields of MP4 container:
tkhd.width = 864
tkhd.height = 480
avc1.width = 720
avc1.height = 480
pasp.hSpacing = 6
pasp.vSpacing = 5

**Comment by cmdrkotori** [comment]
Can you upload a sample video thanks.

**Comment by nu774** [comment]
It seems that the issue is not MP4 specific, and actually I think you can check with any DVD (always coded with 720x480 and anamorphic). Have you tried to play SD video with mpc-qt?

Anyway, I have uploaded  a sample:
https://drive.google.com/file/d/11jPQcBzi4AKh3C08iwff3m3Ey8kJs-Ie/view?usp=sharing
