### ISSUE TITLE
[macOS] System-wide shortcut for closing the app is used by Quick Open File

### ISSUE THREAD

**Issue by albertosottile** [cmdrkotori/mpc-qt#236]
Currently the system-wide shortcut used to close any software ⌘Q is overwritten by the Quick Open File feature in `mpc-qt`. I am sure that probably some other shortcuts overlap, but this is quite critical because ⌘Q is well known and used by many macOS users. 

If possible, I would advise to change the shortcut for Quick Open File on macOS.

Screenshots attached:

![a](https://user-images.githubusercontent.com/7440277/51859568-b9ddb900-2337-11e9-90c5-fdfc1ae6a64c.jpg)
The system-wide shortcut.

![b](https://user-images.githubusercontent.com/7440277/51859571-bba77c80-2337-11e9-90b8-8d30e74e261b.jpg)
Currently used File menu, with the Quick Open File command and shortcut highlighted.

**Comment by albertosottile** [comment]
Apparently, the commit did not fix this bug and I have no idea why. I tried to change the shortcut in these two lines in `mainwindow.cpp`
```
QString quickOpenKeys = Platform::isMac ? tr("Alt+K") : tr("Ctrl+K");
ui->actionFileOpenQuick->setShortcut(quickOpenKeys);
```
and I even tried to comment that and rebuild locally, but no matter what I do, Quick Open File still keeps its ⌘Q shortcut.

@cmdrkotori Any suggestions?

**Comment by albertosottile** [comment]
**UPDATE:** I had to manually delete all the preferences from `~/Library/Preferences/mpc-qt` before actually seeing the change. I guess the issue can stay closed.

**Comment by cmdrkotori** [comment]
Yeah, it's because I decided only on changing the default keyconfigs, which get saved after the first exit into the prefs file. I probably should have included a note about that in the commit, sorry.
