### ISSUE TITLE
[macOS] mainwindow size is wrong on first run

### ISSUE THREAD

**Issue by albertosottile** [cmdrkotori/mpc-qt#238]
See screenshot for further details. After resizing the window manually, closing the app, and reopening it, the window correctly remembers the chosen size.

![screen shot 2019-01-29 at 13 11 44](https://user-images.githubusercontent.com/7440277/51907553-76329000-23c7-11e9-84c7-33f5f39e90f3.png)

In addition, when the app is closing (e.g. by pressing ⌘Q)  the window quickly resizes to a more correct size for a second, then of course it closes.

**Comment by cmdrkotori** [comment]
Yeah I just checked Windows and it happens there too. It's probably exactly the same code path for `geometry.json`. :crossed_fingers:
