### ISSUE TITLE
Allow queuing a playlist entry multiple times

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#24]
Simply so it gets played multiple times.

If this requested is accepted, there are two implementation choices:
- add a per-playlist entry repeat setting
- allow an entry truly to be queued multiple times (i.e. it could appear multiple times on arbitrary positions in the virtual list of queued entries)

**Comment by cmdrkotori** [comment]
I went with storing the current play count logic from the playback manager into the items themselves. This has the advantage that ordinary items and quick queued items can be played however often.

**Comment by wm4** [comment]
I guess this somehow ties in with "Extra Play Times". Seems to work for me.
