### ISSUE TITLE
View>OSD Drop down Menu Setting does not remain set after closing player

### ISSUE THREAD

**Issue by jmaeshawn** [cmdrkotori/mpc-qt#241]
I'm using v18.08, and want to change the option in the "View>OSD" drop down menu to "No Messages" which works at first.

However, it looks like this setting does not get saved across sessions, because after the player is closed and reopened, the OSD setting reverts back to "Application Messages".

![clipboard image](https://user-images.githubusercontent.com/6907886/52383031-7e747600-2a2c-11e9-9cc5-040212eae865.png)

Please fix this bug so that the OSD setting will remain active even after the player is closed and reopened.

**Comment by MeAKAErik** [comment]
Came to post this.
