### ISSUE TITLE
(ubuntu noob) installation failure

### ISSUE THREAD

**Issue by inexplicabro** [cmdrkotori/mpc-qt#242]
i tried installing mpc-qt using these commands:
```
sudo apt-get install qtcreator
sudo apt-get install qt5-default
sudo apt-get install libqt5x11extras5-dev
sudo apt-get install qttools5-dev-tools
sudo apt-get install libmpv-dev
mkdir src
cd ~/src
git clone https://github.com/cmdrkotori/mpc-qt.git
cd mpc-qt
```

then, the next command is `qmake`. when i do that, i get [this](https://i.imgur.com/GkHEVV8.png).
the next command, `make -j threads` is met with [this](https://i.imgur.com/6elZ2lb.png).

what do i do?

**Comment by cmdrkotori** [comment]
*threads* is the output of `cat /proc/cpuinfo | grep 'processor' | wc -l`

**Comment by inexplicabro** [comment]
sorry, still don't understand...

**Comment by inexplicabro** [comment]
> _threads_ is the output of `cat /proc/cpuinfo | grep 'processor' | wc -l`

sorry, i still dont understand...

**Comment by cmdrkotori** [comment]
nono, you only need to do `make -j 8`, not `make -j threads 8`.
That specific error (missing qplatformnativeinterface header) means that you need the qt5 private headers.
It should be a dev package.
Try `apt search qt private`. It should look like `qtbase5-private-dev` or some such.

**Comment by inexplicabro** [comment]
got it! thanks... Is there a key to minimize the player, like in MPC-HC when you press 'b'?
