### ISSUE TITLE
"Prefer external subtitles" Option

### ISSUE THREAD

**Issue by kaitoux1412** [cmdrkotori/mpc-qt#249]
There would be a chance of adding such option to the player? It is a nice option on MPC-HC and would be nice having here. Sorry if it was already planned/suggested.

Adding two non-related questions to not make another post.
Track preferences are there but greyed out so they are already planned, right?
Also there is any shortcut to delete selected items from a playlist?

**Comment by cmdrkotori** [comment]
>There would be a chance of adding such option to the player?

Sure.

>Track preferences are there but greyed out so they are already planned, right?

Yes. However I'm only one person and my time is limited.

>Also there is any shortcut to delete selected items from a playlist?

I thought I had the delete key as that, but it seems not.
