### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by Baemir** [cmdrkotori/mpc-qt#252]
> mpvwidget.cpp:7:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
>  #include <qpa/qplatformnativeinterface.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:903: mpvwidget.o] Error 1
> make: *** Waiting for unfinished jobs

**Comment by ahjolinna** [comment]
for me the latest git version (mpc-qt and mpv) builds just fine  on openSUSE tumbleweed (using OBS).
What distro are you using?

**Comment by cmdrkotori** [comment]
You need the qt5 private headers mate. Something like this one: https://packages.debian.org/sid/amd64/qtbase5-private-dev

**Comment by Baemir** [comment]
> You need the qt5 private headers mate. Something like this one: https://packages.debian.org/sid/amd64/qtbase5-private-dev

That was it. Did I skip over that prerequisite in the readme, or is it missing? Thanks for replying anyway
