### ISSUE TITLE
Moving/copying entries between playlists

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#26]
I think it'd be nice if entries could be moved and copied between playlists, without having to re-add them manually on a new playlist.

I see the following possibilities (which are not exclusive):
- drag & drop selections of entries to other playlists to copy or move them (this is an "obvious" UI but I wouldn't love it too much since it'd require the mouse and "good aim" with the mouse pointer)
- provide a menu button, key shortcut, or button to copy or move entries, although I'm not sure how it'd select the destination
- provide a menu button (etc.) to add the currently active playlist entry (which may come from another playlist) to the current playlist
- append the current play queue to another playlist (that seems like a nice idea to me because it would provide an easy way to make the current queue "permanent")

**Comment by wm4** [comment]
Works for me.

Small suggestion: pasting should insert it at the current selection, instead of strictly appending it to the end.

Also I don't quite understand what `"Ctrl-Alt_V:    Copy and Queue"` does.

**Comment by cmdrkotori** [comment]
Ah that was a typo. It should be "Paste and Queue". It's the same as pasting, but also immediately adds them to the playlist's quick queue.
