### ISSUE TITLE
Restore window layout on restart

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#27]
When starting the player, it should restore the view settings from the last session, such as:
- window position and state
- enabled sub-windows (from the View menu, like status, playlist, etc.)
- layout and position of those sub-windows

Please disregard if Qt makes it too much of a pain to get it right. It's mostly a cosmetic issue.

**Comment by cmdrkotori** [comment]
It should work now, provided the remember geometry checkbox in the front page of the settings dialog is checked.
