### ISSUE TITLE
Wheel doesn't work in full-screen mode

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#33]
As per subject, unless I'm doing something wrong.

**Comment by cmdrkotori** [comment]
Works on my machine. Multi-monitor/Ubuntu16.04/Qt 5.5.1/kwin and Single-monitor/Win7/Qt 5.6.0

I suspect this is just a misconfigured dotfile. Perhaps your `keys.json` file is corrupt, or the shortcut is not mapped. You can get the default back by deleting the corresponding json file in `~/.config/mpc-qt`.

The other likely cause is the wm/whatever not forwarding scroll events. (this usually is not a problem on X.) What is your wm and distro? Also, please attach your `keys.json` file. There's a possibility that I may be able to reproduce this.

**Comment by luigino** [comment]
I'm using kwin 4.11 on openSUSE 13.2, Qt 5.4.2.

Seek via wheel works correctly in window mode.

[keys.json.txt](https://github.com/cmdrkotori/mpc-qt/files/344547/keys.json.txt)

**Comment by cmdrkotori** [comment]
It needs to be set for fullscreen too. (Fourth column of keys page in the settings dialog.)

**Comment by luigino** [comment]
Ouch, sorry.

**Comment by cmdrkotori** [comment]
No problem, mate.  The program should have had an option to ignore the fourth column anyway.
