### ISSUE TITLE
GUI controls in fullscreen mode

### ISSUE THREAD

**Issue by Frechdachs** [cmdrkotori/mpc-qt#36]
The option to enable the GUI controls seems to be just a stub. Would be great if that can be implemented.

**Comment by cmdrkotori** [comment]
This involves reparenting the controls under one widget and supporting show that parent above the gl widget when necessary. (if I were to do it exactly as implemented by mpc-hc.)

I'll get to this in a little bit.

**Comment by Frechdachs** [comment]
Yeah, it would be nice if it worked like in mpc-hc. Baka MPlayer did it in a rather suboptimal way. Stacking the video on top of the controls and resizing the video in the process.

**Comment by cmdrkotori** [comment]
Implemented almost exactly as stated, except the playlist window is not affected by the time out. Use the hide panel option to hide it.

**Comment by Frechdachs** [comment]
Thank you, works very well on my laptop that's running Cinnamon.

However there are some problems on my desktop (i3):
I have two monitors one in front of me (2560x1440) and one on my left side (1920x1080).
Now when switching to fullscreen, only 2/3 of the seekbar is shown. I _assume_ the problem is that it tries to span over the full width of both monitors (4480).
The second problem is that on my secondary monitor moving the mouse will not show the controls at all.

**Comment by cmdrkotori** [comment]
>Now when switching to fullscreen, only about 2/3 of the seekbar is shown.

The bottom area is 80 pixels high (on my machine) and is likely offscreen on the second monitor, if it is there at all.

>I assume the problem is that it tries to span over the full width of both monitors (4480).

I make a best guess based off the screen geometry. I can't discover the exact window size when it gets fullscreened, because the window is actually resized sometime after I ask. So it measures the dimension of the current screen and calculates the geometry of the bottom section from that. Which of course isn't correct if it is ending up on two monitors.

>The second problem is that on my secondary monitor moving the mouse will not show the controls at all.

This is unexpected. But the program should only show one screen anyway. I'll see what I can do.

**Comment by cmdrkotori** [comment]
Please tell me if this worked.

**Comment by Frechdachs** [comment]
Unfortunately, it did not.

>But the program should only show one screen anyway.

It does only show on one screen, only the controls seem to be wider.
I'm not sure, I described the problem I'm experiencing clearly enough, so I made some screenshots of both of my screens.

This shows mpc-qt in fullscreen and the red arrow points to the current position of the seekbar:

https://0x0.st/aVS.png

Now when I exit fullscreen, the seekbar is at a completely different position:

https://0x0.st/aVQ.png

I _think_ the seekbar is too long in fullscreen and just gets cut off.

On my secondary screen, no controls are shown at all:
https://0x0.st/aV1.png

Since your last commit (https://github.com/cmdrkotori/mpc-qt/commit/4a3ff1b5c41515074148213ac7827ae62b17bc79) there is another (visual) bug as demonstrated by the following video:

https://0x0.st/aVB.webm

Before that commit, this didn't happen. Also, it only happens in fullscreen. In windowed mode the dotted lines don't jump from one button to another.

**Comment by Frechdachs** [comment]
Just tried a live DVD of Manjaro with KDE Plasma 5 and Qt 5.7.

Almos exactly the same problems as described above. Only the last one (https://0x0.st/aVB.webm) I couldn't reproduce.

**Comment by Frechdachs** [comment]
>Since your last commit (4a3ff1b) there is another (visual) bug as demonstrated by the following video:

>https://0x0.st/aVB.webm

>Before that commit, this didn't happen. Also, it only happens in fullscreen. In windowed mode the >dotted lines don't jump from one button to another.

Just rebuild without the newest commit and apparently, this still happens before 4a3ff1b, which is strange. I'm sure I would have noticed this earlier ...

**Comment by cmdrkotori** [comment]
Was able to reproduce with the second monitor open.

I'll be away for a week on holiday as of tomorrow.

**Comment by Frechdachs** [comment]
Much appreciated, the seekbar works fine now.
