### ISSUE TITLE
Audio stalls when playing video while mpc-qt is not visible

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#42]
If mpc-qt is not visible due to e.g. not being on the currently active virtual desktop, I get occasional audio dropouts. This happens because mpc-qt uses opengl_cb, but while the window is not visible, will not call video rendering. The consequence is that mpv stalls everything for a while, and then times out. (Actually not sure why it stalls at all.)

Apparently Qt intentionally ignores update calls while the window is not visible. I haven't found a way to disable this "clever" feature.

**Comment by wm4** [comment]
Audio stalls are fixed with https://github.com/mpv-player/mpv/commit/af103aebd73609fa143b07805082a23525c8a306.

**Comment by cmdrkotori** [comment]
Well I guess it's academic that I couldn't reproduce this on kubuntu16.04+backports using kwin+mesa(oibaf)+radeon (r7 250). When I minimize and switch virtual desktops, the audio keeps playing and I get an increased framedrop count when I come back.

It might be present on newer versions of Qt, but I presently cannot test for it; my main video card died yesterday, (gtx 550ti,) so I presently can't pass a second video card through to debian sid or windows. A new radeon card should arrive in the mail this coming week or the next, so I should be able to have a proper look into this on a new Qt version then.

**Comment by wm4** [comment]
It also depends in the exact size of the audio API's buffer.

You can enable verbose logging. Then you should see a `mpv_opengl_cb_draw() not being called or stuck.` message every time that function isn't called after 200ms. (I don't remember why this message is verbose and not a warning or error.)

Not sure if Qt changed anything about this recently. I tested with Qt 5.6.

**Comment by cmdrkotori** [comment]
I reproduced it and fixed it using a workaround.

**Comment by wm4** [comment]
Doesn't work here. I don't think Qt considers being on an inactive workspace to be "minimized".

The method to get the frame drawn seems a bit messy, but that's probably as good as it gets. (It should probably check whether the context exists, just in case, but not sure.) Can I take this code and add it to the mpv Qt example? This would require relicensing it under https://github.com/mpv-player/mpv-examples/blob/master/libmpv/Copyright.

**Comment by cmdrkotori** [comment]
>I don't think Qt considers being on an inactive workspace to be "minimized".

In hindsight, I think window()->isHidden() might have been a better voice.

>Can I take this code and add it to the mpv Qt example? This would require relicensing it under https://github.com/mpv-player/mpv-examples/blob/master/libmpv/Copyright.

Go right ahead.

**Comment by wm4** [comment]
I just added this to the mpv Qt example. Unfortunately, `isHidden()` doesn't do the right thing. I can't find any way to do it correctly. I even asked on the qt IRC channel. So this still only checks for minimized only.
