### ISSUE TITLE
Deadlock wqhen pressing 'q'

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#44]
1. Go somewhere in the middle of a playlist
2. Press Q
3. Frozen forever

My playlist edits went to hell as well.

Can I ask why in heaven's name you use locks in GUI code? And even more so R/W locks, which are frequently hard to use correctly.

**Comment by cmdrkotori** [comment]
Sorry about that. Commit 2228b22 had a "fix" for QuededPlaylist::toggle_ that would have made sense if it was the public function.

>Can I ask why in heaven's name you use locks in GUI code? And even more so R/W locks, which are frequently hard to use correctly.

It's mainly there for the iterator used in the search thread. The idea is that multithreaded searches need to not have items removed out from beneath them. So write locks for item add/removal access, and read locks for other access, specifically the iterator.

btw I'll be away for nearly a week visiting a conference.

**Comment by wm4** [comment]
Thanks. I can't comment on the search thing, but on the first look it seemed quite the overkill.
