### ISSUE TITLE
Windows compiled binaries

### ISSUE THREAD

**Issue by Vegeta-Ouji** [cmdrkotori/mpc-qt#47]
Hi, thanks for your efforts. I hope you make a windows releases for each release of this player. 

Also, is it possible to make something like CCCP out of this player?

thanks

VEGETA

**Comment by cmdrkotori** [comment]
A release is fine too.

I feel like it's a bit too much of a beta to warrant releases though. Unwired gui elements isn't pretty, and I don't want it get a bad reputation before it's off the ground. So I encourage my users to compile it themselves.

>is it possible to make something like CCCP out of this player?

In theory, yes. The filter module when it gets written would duplicate most of the functionality of the avfilter tray icons. So watch this space.

**Comment by Vegeta-Ouji** [comment]
I don't mind using the program in its beta or alpha stage. I can not compile by myself right now. And the user actually knows it is alpha or beta.

**Comment by Vegeta-Ouji** [comment]
hi

why would you close it? it is an open problem to me and the others.

**Comment by AsukaLangleyfag** [comment]
To build, try `pacman -S mingw-w64-x86_64-qt5 mingw-w64-x86_64-pkg-config mingw-w64-x86_64-mpv mingw-w64-x86_64-qt-creator` in msys2. Next, start mingw64.exe and proceed as usual. You'll find the directory in the Qt Creator (for some reason it wasn't */mpc-qt/build-mpc-qt for me, but ../build-mpc-qt-Desktop_Qt_MinGW_w64_64bit_MSYS2-Release/release, but it works, if you need to make it standalone, you'll need to copy required libs [list included](https://github.com/cmdrkotori/mpc-qt/files/648966/out.txt) (you can take imageformats and platforms from c:\msys64\mingw64\share\qt5\plugins\ if you have msys2 installed by default and you're using 64-bit version and other in c:\msys64\mingw64\bin\). That's all you need i think, at least it works for me. And btw you can easly remake that list into a bat to not copy every single file manualy. Good luck!
