### ISSUE TITLE
Ability to "queue" playlist entries, or extended playlist management

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#5]
Often you want to say "play this entry, then play that entry". You could just add a new playlist for it, but adding the entries would be a bit inconvenient. So I see 2 things that could be done:

1. Add an in-playlist "queue" feature. For example crappy old xmms1 had this: you could press the "q" key on a playlist, and the entry would be added to the playback queue. Pressing "q" on another entry would queue it as second entry etc. Each playlist entry had the queue position as a number on the right side of the playlist.

2. Add a simple way to append a playlist entry to another. So you could add the current entry on playlist 1 to playlist 2 with s single click or pressing a key. Though I have no idea how mpc-qt would know to _which_ target playlist to add the entry. This is probably almost an orthogonal feature to 1.

**Comment by cmdrkotori** [comment]
Fixed as of `b7e9c38`.

**Comment by wm4** [comment]
Yep, this seems pretty nice.
