### ISSUE TITLE
Window geometry is not kept

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#53]
Unless I misunderstand what "remember last window geometry" means, everything is re-set to default
at every launch, be it the main window or internal ones.

(mcp-qt trunk on openSUSE Leap 42.2, Qt 5.6.1)

**Comment by cmdrkotori** [comment]
iirc, at present the program applies last remembered geometry and then applies the autozoom code. I'll look into seeing if this behaviour can be switched off at launch.

In the meantime you can uncheck center window in the options, and turn off auto zoom in options or with its shortcut Alt+0. These affect the startup location and size repectively.

**Comment by luigino** [comment]
> iirc, at present the program applies last remembered geometry and then applies the autozoom code. 

But then why do I have the options window like [this](http://i.imgur.com/1GYvwkn.jpg) when I set it like [this](http://i.imgur.com/K1vA1eZ.jpg) the previous time?

**Comment by cmdrkotori** [comment]
>But then why do I have the options window like this when I set it like this the previous time?

I wasn't saving the geometry of the options window. Sorry about that.
