### ISSUE TITLE
Improve High DPI support in options dialog

### ISSUE THREAD

**Issue by Vaporeon** [cmdrkotori/mpc-qt#58]
Currently the options dialog has a horizontal scrollbar on the left list when using a high DPI setting.

![screenshot_2017-01-07_20-35-32](https://cloud.githubusercontent.com/assets/12814075/21740805/f13addb6-d518-11e6-8700-bda5a7c507c3.png)

**Comment by cmdrkotori** [comment]
Please tell me if this fixed the behavior.

**Comment by Vaporeon** [comment]
Seems to still be an issue and the width is actually slightly narrower than the above image. Tried fresh configs to be sure.

**Comment by cmdrkotori** [comment]
I'll do a little bit of guru meditation about this. Please understand that I do not have a highdpi display and could not reproduce this with the right environment variables, so I'll be taking a best guess what the issue could be. Please wait warmly.

**Comment by wm4** [comment]
Looks fine here: https://0x0.st/fTv.png

Did you set the QT_AUTO_SCREEN_SCALE_FACTOR=1 environment variable? Without Qt fucks up hidpi.

**Comment by cmdrkotori** [comment]
I can't reproduce this.
