### ISSUE TITLE
Main window position is not being remembered

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#60]
Every time I load a new file, the window is resized and moved to the center of the screen even if the "remember window geometry" option is set.

**Comment by cmdrkotori** [comment]
The setting for moving the window to the center or not is under Options->Playback->Center window.
To not manipulate the window during start events, press Alt+0 or View->Zoom->Disable snapping.
Remember window geometry decides if the window size and positions are restored at startup.
