### ISSUE TITLE
Feature request: being able to use secondary subtitles

### ISSUE THREAD

**Issue by AsukaLangleyfag** [cmdrkotori/mpc-qt#62]
Well, mpv have this feature: https://mpv.io/manual/master/#subtitles , so why not

**Comment by cmdrkotori** [comment]
Do you have a sample file I can download to test? I've looked through my ~3Tb collection of videos and can't find a single srt.

**Comment by cmdrkotori** [comment]
Never mind, tested using mismatching subs on an avi file. Patch incoming.
