### ISSUE TITLE
selections for methods to disable screensaver

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#67]
it would be nice to have an option to enable the option's to disable screensaver when mpc-qt is in fullscreen and/or video is playing

apprently gnome uses their own thing and kde uses freedesktop standards.. (ironically)..I think, I would check (again) how bomi-player has done it
...I saw:
"org.gnome.SessionManager.Inhibit
"org.freedesktop.screenSaver.Inhibit"
&
"XScreenSaver

**Comment by cmdrkotori** [comment]
Fixed, except on Macs which have a stub. Someone else may have to write that. (My Mac support is untested and theoretical anyway, but not for a want of trying.)
