### ISSUE TITLE
hw acceleration option support

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#68]
I don't think hw acceleration is enabled automatically or is the option is hidden and I missed it...anyway

at least for linux (cant say about other platforms), there is oc the basic vaapi for intel and vdpau for AMD/Nvidia...BUT, it seems Nvidia has/is moving away from vdpau to [CUVID](http://docs.nvidia.com/cuda/video-decoder/#axzz4b3gZGQRJ) which is CUDA based and cross-platform, and [MPV has started to support it](https://github.com/mpv-player/mpv/commit/2048ad2b8af1becddb70cad2a7adc0361b779443) ...and it seems [ffmpeg has also added support](https://github.com/FFmpeg/FFmpeg/tree/master/compat/cuda), so there isn't any need to use the whole [nvidia video sdk](https://developer.nvidia.com/nvidia-video-codec-sdk) anymore.

perhaps you are tierd of hearing (or like) this but I say it again, check how the bomi-player has done this: 
for example
![image](https://cloud.githubusercontent.com/assets/6993072/23827357/9b0a5308-06ba-11e7-902a-15928eb3b756.png)

---------

you may or may not know but the bomi developer has left, so the project is dead...so I'm hoping that mpc-qt would become the replacement I need/want. and Bomi did a lot of nice things before it died, Requiesce in pace

**Comment by cmdrkotori** [comment]
I have been hesitant to do this because hwdec can produce worse quality video in some cases, but sure.

**Comment by cmdrkotori** [comment]
whoops, wrong button

**Comment by ahjolinna** [comment]
quality thing is true (more or less) ...but it oc depends (codec, api, hardware combo), but at least on nvidia side this hasn't been such a problem*...anyway many don't see the quality difference anyway and just want smooth video/overall experience...with less strain on cpu the better.

*I haven't really tested/seen any quality problems with the new cuvid (using GTX970)

**Comment by cmdrkotori** [comment]
You are quite correct that sometimes hwdec is actually rather useful. I left a (hopefully neutral) note in the ui about it.

**Comment by ahjolinna** [comment]
@cmdrkotori : nice that was fast, I just updated my openSUSE build :D ... could u add to the statics or somwhere info about what or if hwdec is (un)available

**Comment by ahjolinna** [comment]
also why did u call h265 -> "High Efficency Video Coding" and not just h265/x265 or HEVC ...which more people would recognize ...just a small thing

**Comment by ahjolinna** [comment]
@cmdrkotori : one more thing, in bomi it will disabled those hwdec codec's if your hardware didn't support them...I don't know how it checks it but I think it's nice so people know that what they can and can't use
