### ISSUE TITLE
"toolbar->file->Properties" broken? 

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#69]
when I try to press the properties or/and Shift+f10 (pic below) nothing happens, doesn't matter if I have video playing or not

![image](https://cloud.githubusercontent.com/assets/6993072/23827608/c223e4ae-06bf-11e7-94e4-cea6d13378a3.png)

**Comment by cmdrkotori** [comment]
This can be implemented by using of libmediainfo.

**Comment by ahjolinna** [comment]
@cmdrkotori : u mean this hasnt yet been implemented? or I need to install libmediainfo...as I tried to install it and it didn't work.

**Comment by cmdrkotori** [comment]
It hasn't been implemented (yet), and yeah you will need libmediainfo when it's done.

As respects to mediainfo, the library has slightly different naming convention on windows than on linux. So I'll be prioritizing the Linux install first before I work on getting it running on Windows. (those poor mac users will be getting yet another stub.)

**Comment by wm4** [comment]
(I wouldn't use mediainfo...)

**Comment by cmdrkotori** [comment]
>(I wouldn't use mediainfo...)

Of course, mediainfo provides the laziest way to produce exactly the same output as mpc-hc. On the other hand, this isn't a direct clone because I already provide extra features they don't have so who cares if it doesn't look exactly the same.

But as it is from what I gathered by a quick perusal of their properties window, some info in the first tab is not taken from mediainfo. So I would be taking info from mpv anyway.

Eh, I'll see what I can do.

**Comment by wm4** [comment]
I don't mind if mpv isn't used for this, but I have... mixed opinions about mediainfo. I think its output is more often than not misleading to users.

**Comment by ahjolinna** [comment]
are there any better replacements/options? I personally think mediainfo is more than fine at least for normal users and I don't think more "advance users" will care that much ...pro/experts/nerds etc...they will, but they have always their own thing...so who cares

**Comment by wm4** [comment]
You could call ffprobe (in json mode for easier consumption). Yeah, maybe it's easier to just use libmediainfo.

**Comment by cmdrkotori** [comment]
I've made a partial fix to this issue and pushed it to master. So far I haven't needed to use any data other than what mpv provides, and I'm going to attempt to use as much information from mpv as I can for the last tab, because I'd like to avoid any more dependencies if I can avoid them.

**Comment by cmdrkotori** [comment]
Fixed, and no mediainfo library needed.

![screenshot_20170516_234650](https://cloud.githubusercontent.com/assets/11322485/26109768/9477c392-3a93-11e7-9b84-1e6e92d9a7c8.png)

**Comment by wm4** [comment]
(Neat!)
