### ISSUE TITLE
[suggestion] simplify/cleaner UX

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#70]
I like what you have done so far, but only complaint I have is that the UI/UX seems really "restless, incoherent, disorganized" ... I know that you go for the MPC style as it's a Qt clone but if my memory serves right (maybe not) it wasn't this "disjointed" .

...I mean no offence, it's just now it looks like its designed by a (software) engineer...and that will make the mainstream user find it off putting to use.

I recommend look at some visual guidelines and try to take some hints/inspiration from them,
for example KDE has made good job : [link](https://community.kde.org/KDE_Visual_Design_Group/HIG)

NOTE: I'm not saying that you need to follow those (kde) guidelines exactly/directly just vaguely ...as they are guidelines not rules

**Comment by cmdrkotori** [comment]
Thanks for the link. I've made a few changes to the settings window layout.  I'll see if I can find some time to research ux principles in proper and hopefully make more finer adjustments.
