### ISSUE TITLE
Subtitle options don't change anything

### ISSUE THREAD

**Issue by mooop12** [cmdrkotori/mpc-qt#73]
Changing any of the subtitle options does not change the actual subtitles.

**Comment by cmdrkotori** [comment]
Works on my machine.

What version of (lib)mpv are you using?

**Comment by mooop12** [comment]
Just compiled the latest from git, didn't fix it. Also rebuilt mpc-qt and removed the settings file, just to be sure.

```
mpv git-c68be80a63 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Mar 30 00:56:17 CEST 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4
```

**Comment by cmdrkotori** [comment]
What's the video file you're using? Might be a corner-case that I haven't thought of. It works with The Garden of Words.

![screenshot_20170330_093923](https://cloud.githubusercontent.com/assets/11322485/24481384/402ffdf8-152d-11e7-960c-09c303e13085.png)
![screenshot_20170330_093947](https://cloud.githubusercontent.com/assets/11322485/24481392/4e45e330-152d-11e7-9aed-ce438b80ced4.png)

**Comment by mooop12** [comment]
I tried many different movies, with integrated subtitles as well as external, all of them used the default font and ignored the subtitle settings.

Is there a way to see what options are passed to mpv by mpc-qt? I know the subtitles work when I run mpv standalone and set the settings manually.

**Comment by cmdrkotori** [comment]
Subtitle overrides aren't implemented yet. Might get done anywhere from the end of today to several weeks time. Sorry, irl is busy.

**Comment by cmdrkotori** [comment]
Options for default style (i.e. srt subs) should work now. Fleshing out a sane ui for (the rest of the) ass overrides will require more thought than I'm prepared to put in right now, so maybe another day.

**Comment by mooop12** [comment]
Thanks. Could you also add the placement options? Override position, use margins etc. I use it so the subs are in the same place whether the player is fullscreen or windowed.
