### ISSUE TITLE
Video is too small when QT_DEVICE_PIXEL_RATIO=2

### ISSUE THREAD

**Issue by rossy** [cmdrkotori/mpc-qt#8]
Seems like the video sticks to the bottom-left corner on HiDPI displays

![mpc-qt-hidpi](https://cloud.githubusercontent.com/assets/162837/14422830/0538cf08-001c-11e6-8f2d-3d9970b82e09.png)

**Comment by cmdrkotori** [comment]
Fixed in 5338924.

**Comment by rossy** [comment]
It works, thanks.
