### ISSUE TITLE
Drag URLs to window

### ISSUE THREAD

**Issue by voxadam** [cmdrkotori/mpc-qt#81]
I've been using mpc-qt to watch YouTube videos instead of using the traditional web interface because, well, I prefer it and for some reason Firefox ends up consuming all of my 32 gigs of physical memory when watching videos.

In any case, it would be great if I could click-and-drag URL to the mpc-qt window. Bonus points if the behavior of dropping links was configurable. For instance, the video could be played immediately upon dropping the link, it could load the video in a paused state, or it could be added to the current playlist.

**Comment by voxadam** [comment]
I just noticed that dragging a URL to the windows _does_ work. What I noticed that it only works if a video has already been loaded. If the app has been loaded but no video has been played the drag-and-drop fails.

**Comment by cmdrkotori** [comment]
Works on my machine. Dragging on the url works every time.

Bear in mind that it won't play immediately if you drag it on to the playlist window, it'll end up on the playlist.
