### ISSUE TITLE
wont build on obs/opensuse

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#82]
I just tried to update mpc-qt on obs with the latest commit 04c3421 a day ago, but it wont build anymore on leap42.2 or tumbleweed but it builds just fine on manjaro(-kde)

logs:
[leap42.2-log.txt](https://github.com/cmdrkotori/mpc-qt/files/1002144/leap42.2-log.txt)
and
[tumbleweed-log.txt](https://github.com/cmdrkotori/mpc-qt/files/1002146/tumbleweed-log.txt)

**Comment by cmdrkotori** [comment]
Should be fixed now.
