### ISSUE TITLE
--size argument being ignored

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#89]
Unless for very large values, in which case the window is maximised in either dimension.
In my case it seems to be the full resolution for the width, but somewhat less for the height, I couldn't find a meaning relation to the vertical screen size of screen or viewport.

**Comment by cmdrkotori** [comment]
Can confirm, restoring window sizes through the commandline doesn't work. It was an ugly kludge and I'm not surprised that it broke.

**Comment by cmdrkotori** [comment]
What is your opinion on client side decorations? I'm inclined to take control away from the window manager because the init code appears to be making too many size adjustments that makes X spaz out. It would also allow me to support all the window types that mpc-hc has.

Here's  a mock-up I have working (needs a bit of polish): https://a.doko.moe/zjgfry.webm

**Comment by cmdrkotori** [comment]
Yes it will. However through some blind luck I'm very close to fixing the original code, so that might not be necessary.

**Comment by luigino** [comment]
Do I need to open a new ticket for the X11 positioning bug to be addressed?

**Comment by cmdrkotori** [comment]
No, should be fixed now. Would be fixed earlier, but I was procastinating.

**Comment by luigino** [comment]
Using 17.08: --size and --pos are seemingly still being ignored on openSUSE linux and if I move the window via wmctrl it moves back to a hardcoded position with the origin near the center of the screen, paused.

This with a clean profile and with "remember last geometry" unset.

**Comment by luigino** [comment]
17.09 seems to fix most of the problems but --size still cannot reduce the window to the vertical minimum, that is covering the video part.

**Comment by cmdrkotori** [comment]
Like this?

![screenshot_20170927_202631](https://user-images.githubusercontent.com/11322485/30908804-22a12180-a3c2-11e7-9589-1cc938b5a0a6.png)

You either have to undock the playlist or dock it at the top/bottom, and then disable zoom snapping.

**Comment by luigino** [comment]
I'd like it to be like this:
![mpc-qt_ilike](https://user-images.githubusercontent.com/1450716/30911411-ce71b144-a388-11e7-92ba-f7195ce8c728.jpg)

According to xwininfo, the vertical size is 128px, but if I run `mpc-qt  --size 600,128`, I see this instead:
![mpc-qt_idontlike](https://user-images.githubusercontent.com/1450716/30911455-f6a608fe-a388-11e7-8ce2-eb58fa13621f.jpg)

The playlist is disabled, not sure what you mean by zoom snapping.

**Comment by cmdrkotori** [comment]
By zoom snapping I meant "disable snapping" (Alt+0) under the View->Zoom menu.

**Comment by luigino** [comment]
https://github.com/cmdrkotori/mpc-qt/commit/8ada2f2e17f961dc1679c18cc29ce35f5a913922 did the trick, TYVM.

**Comment by luigino** [comment]
I have to correct myself: it works only when no file is passed as argument. If it is, the window is autoadapted even when snapping is disabled.
