### ISSUE TITLE
Remember last window geometry is being ignored

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#92]
Window is always resized to video resolution.

**Comment by cmdrkotori** [comment]
This is probably related to #89 too.

**Comment by cmdrkotori** [comment]
OH I forgot to mention that remember window geometry will be overridden every time unless zoom snapping is disabled (View/Zoom/Disable Snapping - default: alt+0)

**Comment by luigino** [comment]
> OH I forgot to mention that remember window geometry will be overridden every time unless zoom snapping is disabled (View/Zoom/Disable Snapping - default: alt+0)

That was the problem. TYVM.
