### ISSUE TITLE
mpc-qt in fullscreen "vanishes" when the next in playlist starts playing 

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#94]
I don't know why now, but everytime mpc-qt is in fullscreen and the next video in the playlist starts playing it just vanishes..'puff'..I mean really it just "vanishes", I only hear the audio in the background -_-'' ?

maybe Qt5.9 thing?

here is the gdb log : [mpc-qt-log.txt](https://github.com/cmdrkotori/mpc-qt/files/1058520/mpc-qt-log.txt)

```
inxi -b
System:    Host: arch-anywhere Kernel: 4.11.3-4-lqx x86_64 (64 bit) Desktop: KDE Plasma 5.10.1
           Distro: Arch Linux
Machine:   Device: desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x UEFI: American Megatrends v: 2003 date: 09/19/2016
CPU:       Quad core Intel Core i5-6600K (-MCP-) speed: 3501 MHz (max)
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 970/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 381.22
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e
Drives:    HDD Total Size: 12129.8GB (94.5% used)
Info:      Processes: 295 Uptime: 9:42 Memory: 5052.5/15988.6MB Client: Shell (bash) inxi: 2.3.12 
```

PS. I'm also using [ffmpeg-full](https://aur.archlinux.org/packages/ffmpeg-full) and [mpv-full](https://aur.archlinux.org/packages/mpv-full)

**Comment by ahjolinna** [comment]
sigh, now I notice that when mpc-qt is in maximised "window mode", and the next video start playing in the playlist...this happnes:
![image](https://user-images.githubusercontent.com/6993072/26909805-f3613be8-4c0b-11e7-9399-94224c06323c.png)

**Comment by cmdrkotori** [comment]
Was caused by an artifact of the resizing refactor.

Sorry about the wait, the next three weeks will be rather busy for me.
