### ISSUE TITLE
Windows compiled binaries

### ISSUE THREAD

**Issue by brucethemoose** [cmdrkotori/mpc-qt#95]
Duplicate of this issue, which is closed:

https://github.com/cmdrkotori/mpc-qt/issues/47

However, I've been using a pre-compiled binary from another source on Windows for quite some time. Mpc-qt has been nothing but stable and feature-packed for me... In the near future, would some kind of release or beta be in the cards?

**Comment by cmdrkotori** [comment]
>In the near future, would some kind of release or beta be in the cards?

Sure. I was going to wait until a more appropriate time for more complete releases, but apparently time-based builds are the way it's done in Windows land despite the wishful thinking of developers. I'm thinking around the beginning of July starting from next month and every six months or so. Of course this would mean 17.07 would be the first build.

**Comment by brucethemoose** [comment]
Cool, thanks. Yeah, even if it seems less logical,  those periodic binary releases are nice to have. 

I see lots of posts about borked MPC-HC installs these days (people tend to follow outdated YT vids, download prehistoric codec packs etc), so I'm looking forward to an official QT release to point people towards. It may be unfinished from your perspective, but it's a self contained, bomb-proof player with all the right features from mine :P

**Comment by lanzorg** [comment]
> Of course this would mean 17.07 would be the first build.

Tomorrow? ;-)

**Comment by cmdrkotori** [comment]
Fixed via the release page.

>Tomorrow? ;-)

Depends on the timezone. ;-)
