### ISSUE TITLE
  About loading subtitles

### ISSUE THREAD

**Issue by zyb920** [cmdrkotori/mpc-qt#96]
The video is playing, 
and then loading a subtitle file will not success。

void MainWindow::on_actionFileLoadSubtitle_triggered()
{
    mpvw->setSubFile("file:///F:/play_source/subtitle/a.srt");
}

**Comment by zyb920** [comment]
void MainWindow::on_actionFileLoadSubtitle_triggered()
{
    mpvw->setSubFile("file:///F:/play_source/subtitle/a.srt");
}

**Comment by cmdrkotori** [comment]
Yes, that's not written at present. In the meantime, `File->Open File...` can load a subtitle file along with a single media file.

**Comment by zyb920** [comment]
using  the  mpv player, it's ok....

but  libmpv   can't... ????

**Comment by cmdrkotori** [comment]
Both can, it's the same codebase.

mpc-qt is incomplete.

**Comment by zyb920** [comment]
well, Solved.

#include <mpv/qthelper.hpp>
QStringList list;
list << "sub-add" << "F:/play_source/subtitle/a.srt";
mpv::qt::command(mpv, list);
