### ISSUE TITLE
[Windows release] Some shaders don't work, and print-screening upscaled fullscreen outputs native resolution screenshot upon pasting

### ISSUE THREAD

**Issue by jameshendricks** [cmdrkotori/mpc-qt#98]
adaptive-sharpen.glsl causes a blue screen. SSimSuperRes does absolutely nothing. Print-screening when in fullscreen and watching upscaled content outputs a native resolution screenshot when pasting to Photoshop. This makes using MPC-QT to compare subtle changes in upscaling settings impossible.

**Comment by cmdrkotori** [comment]
>adaptive-sharpen.glsl causes a blue screen.

On my machine, adaptive-sharpen causes a white screen with "Scale In Linear Light" turned on. Might be a problem with the shader. SSimSuperRes does work though. Try turning that off.

>Print-screening when in fullscreen and watching upscaled content outputs a native resolution screenshot when pasting to Photoshop. This makes using MPC-QT to compare subtle changes in upscaling settings impossible.

Windows tends to put fullscreen applications in exclusive mode (i.e. only the application has access to the screen). Under situations like this, printscreening will not work. This is by design. However I can expose mpv's ability to screenshot the video with scaling in fairly quick order.

**Comment by cmdrkotori** [comment]
Turns out that mpv's screenshot window command doesn't work with opengl-cb, so I did the video frame grab myself.

**Comment by cmdrkotori** [comment]
There's a hotfix for this in the releases page.

**Comment by jameshendricks** [comment]
Adaptive-sharpen and SSimSuperRes are still not working on my machine. Switching general video renderer presets to "plain" allowed me to put adaptive-sharpen in the active shaders without a blue screen, but it's having no effect on the image. SSimSuperRes still having zero effect on the image. I've been enabling/disabling pretty much every setting I can find and neither of these shaders are having any effect on the image. Finesharp is an example of a shader I have gotten to work and have an effect on the image.

How do I use the debugging? Maybe I could help find the cause with that.

**Comment by cmdrkotori** [comment]
I reproduced the blue screen with the placebo preset and scale in linear light turned off. Also turning off sigmoidized upscaling returned the display to normal.

>How do I use/read the debugging? Maybe I could help find the cause with that.

At the moment you need to run it from within the developer environment. I suppose in the future it may be possible to create some sort of logging window.

**Comment by brucethemoose** [comment]
Running into similar problems myself atm. Not sure if I downloaded them wrong or what, but AdaptiveSharpen, NNEDI and superXBR are not doing anything to the image atm. 

Same thing happens with my older build though, and I'm sure they were working at one point. Hmmmmm....
